### ISSUE TITLE
[Issue]: ControlNet error with exception handler

### ISSUE THREAD

**Issue by syddharth** [vladmandic/automatic#102]
### Issue Description

Error running preload() for F:\Programs\automatic\extensions-builtin\sd-webui-controlnet\preload.py
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ F:\Programs\automatic\modules\script_loading.py:28 in preload_extensions                                             │
│                                                                                                                      │
│   27             if hasattr(module, 'preload'):                                                                      │
│ ❱ 28                 module.preload(parser)                                                                          │
│   29                                                                                                                 │
│                                                                                                                      │
│ F:\Programs\automatic\extensions-builtin\sd-webui-controlnet\preload.py:2 in preload                                 │
│                                                                                                                      │
│   1 def preload(parser):                                                                                             │
│ ❱ 2     parser.add_argument("--controlnet-dir", type=str, help="Path to directory with Contr                         │
│   3     parser.add_argument("--no-half-controlnet", action='store_true', help="do not switch                         │
│                                                                                                                      │
│                                               ... 4 frames hidden ...                                                │
│                                                                                                                      │
│ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\argparse.py:1592 in _check_conflict                       │
│                                                                                                                      │
│   1591             conflict_handler = self._get_handler()                                                            │
│ ❱ 1592             conflict_handler(action, confl_optionals)                                                         │
│   1593                                                                                                               │
│                                                                                                                      │
│ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\argparse.py:1601 in _handle_conflict_error                │
│                                                                                                                      │
│   1600                                      in conflicting_actions])                                                 │
│ ❱ 1601         raise ArgumentError(action, message % conflict_string)                                                │
│   1602                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ArgumentError: argument --controlnet-dir: conflicting option string: --controlnet-dir

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ F:\Programs\automatic\launch.py:91 in <module>                                                                       │
│                                                                                                                      │
│   90     setup.log.info(f"Server Arguments: {sys.argv[1:]}")                                                         │
│ ❱ 91     import webui                                                                                                │
│   92     webui.webui()                                                                                               │
│                                                                                                                      │
│ F:\Programs\automatic\webui.py:13 in <module>                                                                        │
│                                                                                                                      │
│    12                                                                                                                │
│ ❱  13 from modules import paths, timer, import_hook, errors                                                          │
│    14                                                                                                                │
│                                                                                                                      │
│                                               ... 1 frames hidden ...                                                │
│                                                                                                                      │
│ F:\Programs\automatic\modules\shared.py:34 in <module>                                                               │
│                                                                                                                      │
│    33 script_loading.preload_extensions(extensions_dir, parser)                                                      │
│ ❱  34 script_loading.preload_extensions(extensions_builtin_dir, parser)                                              │
│    35                                                                                                                │
│                                                                                                                      │
│ F:\Programs\automatic\modules\script_loading.py:32 in preload_extensions                                             │
│                                                                                                                      │
│   31             print(f"Error running preload() for {preload_script}", file=sys.stderr)                             │
│ ❱ 32             shared.exception()                                                                                  │
│   33                                                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: partially initialized module 'modules.shared' has no attribute 'exception' (most likely due to a
circular import)
Press any key to continue . . .

### Platform Description

Using windows 11, RTX 4090.

**Comment by vladmandic** [comment]
Should be fixed in the latest update. If not, I'll reopen the issue.

**Comment by razvan-nicolae** [comment]
Error running preload() for I:\SD\automatic\extensions-builtin\sd-webui-controlnet\preload.py
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\script_loading.py:28 in preload_extensions                                                  │
│                                                                                                                     │
│   27             if hasattr(module, 'preload'):                                                                     │
│ > 28                 module.preload(parser)                                                                         │
│   29                                                                                                                │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-webui-controlnet\preload.py:2 in preload                                      │
│                                                                                                                     │
│   1 def preload(parser):                                                                                            │
│ > 2     parser.add_argument("--controlnet-dir", type=str, help="Path to directory with Contr                        │
│   3     parser.add_argument("--no-half-controlnet", action='store_true', help="do not switch                        │
│                                                                                                                     │
│                                               ... 4 frames hidden ...                                               │
│                                                                                                                     │
│ I:\SD\python\lib\argparse.py:1592 in _check_conflict                                                                │
│                                                                                                                     │
│   1591             conflict_handler = self._get_handler()                                                           │
│ > 1592             conflict_handler(action, confl_optionals)                                                        │
│   1593                                                                                                              │
│                                                                                                                     │
│ I:\SD\python\lib\argparse.py:1601 in _handle_conflict_error                                                         │
│                                                                                                                     │
│   1600                                      in conflicting_actions])                                                │
│ > 1601         raise ArgumentError(action, message % conflict_string)                                               │
│   1602                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ArgumentError: argument --controlnet-dir: conflicting option string: --controlnet-dir

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\launch.py:92 in <module>                                                                            │
│                                                                                                                     │
│   91     setup.log.info(f"Server arguments: {sys.argv[1:]}")                                                        │
│ > 92     import webui                                                                                               │
│   93     webui.webui()                                                                                              │
│                                                                                                                     │
│ I:\SD\automatic\webui.py:23 in <module>                                                                             │
│                                                                                                                     │
│    22                                                                                                               │
│ >  23 from modules import import_hook                                                                               │
│    24 import gradio                                                                                                 │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ I:\SD\automatic\modules\shared.py:34 in <module>                                                                    │
│                                                                                                                     │
│    33 script_loading.preload_extensions(extensions_dir, parser)                                                     │
│ >  34 script_loading.preload_extensions(extensions_builtin_dir, parser)                                             │
│    35                                                                                                               │
│                                                                                                                     │
│ I:\SD\automatic\modules\script_loading.py:32 in preload_extensions                                                  │
│                                                                                                                     │
│   31             print(f"Error running preload() for {preload_script}", file=sys.stderr)                            │
│ > 32             shared.exception()                                                                                 │
│   33                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: partially initialized module 'modules.shared' has no attribute 'exception' (most likely due to a
circular import)
Press any key to continue . . .


Looks like it's still there, never seen anything like it, can't really guess the cause.

**Comment by vladmandic** [comment]
i'll take a look.

**Comment by vladmandic** [comment]
error message is cryptic, but root cause was two fold:
- this fork has controlnet already integrated and some users had different & conflicting version of controlnet manually installed.
- exception handler performing wrong import

i've just posted an update to auto-handle this. if the issue reoccurs,  
please report and i'll reopen the issue.

**Comment by tcflying** [comment]
I still can't start with webui.bat, please help, thanks, error below:

(venv) PS F:\stable-diffusion-webui> .\webui.bat
venv "F:\stable-diffusion-webui\venv\Scripts\Python.exe"
Installing requirements for Web UI
Running extension installer: F:\stable-diffusion-webui\extensions\clip-interrogator-ext\install.py
A Installing requirements for CLIP Interrogator

Running extension installer: F:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\ebsynth_utility\install.py
A current transparent-background 1.2.3

Running extension installer: F:\stable-diffusion-webui\extensions\PBRemTools\install.py
A Installing None
Installing onnxruntime-gpu...
Installing None
Installing opencv-python...
Installing None
Installing Pillow...
Installing None
Installing segmentation-refinement...
Installing None
Installing scikit-learn...

Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-3d-open-pose-editor\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-controlnet\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-nulienhance\install.py
A Installed.

Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-segment-anything\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py
A Stop Motion CN - Running Preload
Set Gradio Queue: True
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 google-auth-oauthlib-0.4.6 tensorboard-2.12.0 transformers-4.26.1
[+] xformers version 0.0.17.dev464 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Running extension installer: F:\stable-diffusion-webui\extensions\stable-diffusion-webui-blip2-captioner\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\stable-diffusion-webui-rembg\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\unprompted\install.py
A Installing requirements for Unprompted - img2pez
Installing requirements for Unprompted - pix2pix_zero

Running extension installer: F:\stable-diffusion-webui\extensions\video2video\install.py
A Installing video2video requirement: sk-video

Launching Web UI with arguments:
F:\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: otobuf is an invalid version and will not be supported in a future release
  warnings.warn(
Stop Motion CN - Running Preload
Set Gradio Queue: True
Error running preload() for F:\stable-diffusion-webui\extensions-builtin\sd-webui-controlnet\preload.py
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\stable-diffusion-webui\modules\script_loading.py:28 in preload_extensions                                        │
│                                                                                                                     │
│   27             if hasattr(module, 'preload'):                                                                     │
│ > 28                 module.preload(parser)                                                                         │
│   29                                                                                                                │
│                                                                                                                     │
│ F:\stable-diffusion-webui\extensions-builtin\sd-webui-controlnet\preload.py:2 in preload                            │
│                                                                                                                     │
│   1 def preload(parser):                                                                                            │
│ > 2     parser.add_argument("--controlnet-dir", type=str, help="Path to directory with Contr                        │
│   3     parser.add_argument("--no-half-controlnet", action='store_true', help="do not switch                        │
│                                                                                                                     │
│                                               ... 4 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\argparse.py:1592 in _check_conflict              │
│                                                                                                                     │
│   1591             conflict_handler = self._get_handler()                                                           │
│ > 1592             conflict_handler(action, confl_optionals)                                                        │
│   1593                                                                                                              │
│                                                                                                                     │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\argparse.py:1601 in _handle_conflict_error       │
│                                                                                                                     │
│   1600                                      in conflicting_actions])                                                │
│ > 1601         raise ArgumentError(action, message % conflict_string)                                               │
│   1602                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ArgumentError: argument --controlnet-dir: conflicting option string: --controlnet-dir

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\stable-diffusion-webui\launch.py:311 in <module>                                                                 │
│                                                                                                                     │
│   310     prepare_environment()                                                                                     │
│ > 311     start()                                                                                                   │
│   312                                                                                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\launch.py:302 in start                                                                    │
│                                                                                                                     │
│   301     print(f"Launching {'API server' if '--nowebui' in sys.argv else 'Web UI'} with argum                      │
│ > 302     import webui                                                                                              │
│   303     if '--nowebui' in sys.argv:                                                                               │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\modules\shared.py:34 in <module>                                                          │
│                                                                                                                     │
│    33 script_loading.preload_extensions(extensions_dir, parser)                                                     │
│ >  34 script_loading.preload_extensions(extensions_builtin_dir, parser)                                             │
│    35                                                                                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\modules\script_loading.py:32 in preload_extensions                                        │
│                                                                                                                     │
│   31             print(f"Error running preload() for {preload_script}", file=sys.stderr)                            │
│ > 32             shared.exception()                                                                                 │
│   33                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: partially initialized module 'modules.shared' has no attribute 'exception' (most likely due to a
circular import)
请按任意键继续. . .

**Comment by vladmandic** [comment]
did you update the repo? either manually or using `--upgrade` flag?

**Comment by tcflying** [comment]
thanks. i am trying now. be back soon.

**Comment by tcflying** [comment]
yes, i have updated to newest repo and now try with  webui.bat --upgrade

**Comment by tcflying** [comment]
(venv) PS F:\stable-diffusion-webui> .\webui.bat --upgrade
venv "F:\stable-diffusion-webui\venv\Scripts\Python.exe"
Installing requirements for Web UI
Running extension installer: F:\stable-diffusion-webui\extensions\clip-interrogator-ext\install.py
A Installing requirements for CLIP Interrogator

Running extension installer: F:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\ebsynth_utility\install.py
A current transparent-background 1.2.3

Running extension installer: F:\stable-diffusion-webui\extensions\PBRemTools\install.py
A Installing None
Installing onnxruntime-gpu...
Installing None
Installing opencv-python...
Installing None
Installing Pillow...
Installing None
Installing segmentation-refinement...
Installing None
Installing scikit-learn...

Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-3d-open-pose-editor\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-controlnet\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-nulienhance\install.py
A Installed.

Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-segment-anything\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py
A Stop Motion CN - Running Preload
Set Gradio Queue: True
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 google-auth-oauthlib-0.4.6 tensorboard-2.12.0 transformers-4.26.1
[+] xformers version 0.0.17.dev464 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Running extension installer: F:\stable-diffusion-webui\extensions\stable-diffusion-webui-blip2-captioner\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\stable-diffusion-webui-rembg\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\unprompted\install.py
A Installing requirements for Unprompted - img2pez
Installing requirements for Unprompted - pix2pix_zero

Running extension installer: F:\stable-diffusion-webui\extensions\video2video\install.py
A Installing video2video requirement: sk-video

Launching Web UI with arguments: --upgrade
F:\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: otobuf is an invalid version and will not be supported in a future release
  warnings.warn(
Stop Motion CN - Running Preload
Set Gradio Queue: True
Error running preload() for F:\stable-diffusion-webui\extensions-builtin\sd-webui-controlnet\preload.py
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\stable-diffusion-webui\modules\script_loading.py:28 in preload_extensions                                        │
│                                                                                                                     │
│   27             if hasattr(module, 'preload'):                                                                     │
│ > 28                 module.preload(parser)                                                                         │
│   29                                                                                                                │
│                                                                                                                     │
│ F:\stable-diffusion-webui\extensions-builtin\sd-webui-controlnet\preload.py:2 in preload                            │
│                                                                                                                     │
│   1 def preload(parser):                                                                                            │
│ > 2     parser.add_argument("--controlnet-dir", type=str, help="Path to directory with Contr                        │
│   3     parser.add_argument("--no-half-controlnet", action='store_true', help="do not switch                        │
│                                                                                                                     │
│                                               ... 4 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\argparse.py:1592 in _check_conflict              │
│                                                                                                                     │
│   1591             conflict_handler = self._get_handler()                                                           │
│ > 1592             conflict_handler(action, confl_optionals)                                                        │
│   1593                                                                                                              │
│                                                                                                                     │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\argparse.py:1601 in _handle_conflict_error       │
│                                                                                                                     │
│   1600                                      in conflicting_actions])                                                │
│ > 1601         raise ArgumentError(action, message % conflict_string)                                               │
│   1602                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ArgumentError: argument --controlnet-dir: conflicting option string: --controlnet-dir

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\stable-diffusion-webui\launch.py:311 in <module>                                                                 │
│                                                                                                                     │
│   310     prepare_environment()                                                                                     │
│ > 311     start()                                                                                                   │
│   312                                                                                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\launch.py:302 in start                                                                    │
│                                                                                                                     │
│   301     print(f"Launching {'API server' if '--nowebui' in sys.argv else 'Web UI'} with argum                      │
│ > 302     import webui                                                                                              │
│   303     if '--nowebui' in sys.argv:                                                                               │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\modules\shared.py:34 in <module>                                                          │
│                                                                                                                     │
│    33 script_loading.preload_extensions(extensions_dir, parser)                                                     │
│ >  34 script_loading.preload_extensions(extensions_builtin_dir, parser)                                             │
│    35                                                                                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\modules\script_loading.py:32 in preload_extensions                                        │
│                                                                                                                     │
│   31             print(f"Error running preload() for {preload_script}", file=sys.stderr)                            │
│ > 32             shared.exception()                                                                                 │
│   33                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: partially initialized module 'modules.shared' has no attribute 'exception' (most likely due to a
circular import)
请按任意键继续. . .

**Comment by vladmandic** [comment]
sorry, but this does not even look like anything that my `webui.bat` would print.
if you have a very old version before `webui.bat` was replaced, then `--upgrade` flag does not exist and you either need to update manually (`git pull --autostash`) or do a fresh clone.
