### ISSUE TITLE
[Issue]: SDP does not work with Tiled VAE

### ISSUE THREAD

**Issue by mart-hill** [vladmandic/automatic#128]
### Issue Description

..then I'll try to generate something with (for example) foolhardy's upscaler (with small tile size, like 256, and not 3072, so the Tiled VAE kicks in), I'll get this error:

```
100%|██████████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.51it/s]
[Tiled VAE]: the input size is tiny and unnecessary to tile.
[Tiled VAE]: input_size: torch.Size([1, 3, 1472, 1030]), tile_size: 256, padding: 32
[Tiled VAE]: split to 6x4 = 24 tiles. Optimal tile size 256x256, original tile size 256x256
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 179 x 256 image
gradio call: NameError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ X:\AI\automatic\modules\call_queue.py:57 in f                                                                    │
│                                                                                                                  │
│    56 │   │   │   │   pr.enable()                                                                                │
│ ❱  57 │   │   │   res = list(func(*args, **kwargs))                                                              │
│    58 │   │   │   if shared.cmd_opts.profile:                                                                    │
│                                                                                                                  │
│ X:\AI\automatic\modules\call_queue.py:36 in f                                                                    │
│                                                                                                                  │
│    35 │   │   │   try:                                                                                           │
│ ❱  36 │   │   │   │   res = func(*args, **kwargs)                                                                │
│    37 │   │   │   finally:                                                                                       │
│                                                                                                                  │
│                                             ... 17 frames hidden ...                                             │
│                                                                                                                  │
│ X:\AI\automatic\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py:196 in <lambda>     │
│                                                                                                                  │
│   195 │   │   task_queue.append(                                                                                 │
│ ❱ 196 │   │   │   ('attn', lambda x, net=net: xformer_attn_forward(net, x)))                                     │
│   197 │   │   task_queue.append(['add_res', None])                                                               │
│                                                                                                                  │
│ X:\AI\automatic\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py:172 in              │
│ xformer_attn_forward                                                                                             │
│                                                                                                                  │
│   171 │   )                                                                                                      │
│ ❱ 172 │   out = xformers.ops.memory_efficient_attention(                                                         │
│   173 │   │   q, k, v, attn_bias=None, op=self.attention_op)                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'xformers' is not defined
```

At this point, I'll have to switch to xformers and restart the UI (because otherwise xformers doesn't kick in), I believe. But then, after doing so and generating an image with xformers, I can switch to SDP, re-load a model (I need to, I think, for the chosen cross-attention-optimization to kick in), and generate an image with the newly chosen SDP AND with Tiled VAE on.

Interesting.

After full UI restart, I have xformers ON:
![image](https://user-images.githubusercontent.com/55754730/232078140-10fef773-dfc9-4d3d-8066-4c7f1c0f35ea.png)

...and the generation of the image will go as planned (with 4x-foolhardy-remacri upscaler hires fix, so VRAM usage is higher to actually "invite" Tiled VAE for some work at 1024x1472 resolution):
![image](https://user-images.githubusercontent.com/55754730/232078906-6da8de48-da0c-4ed9-b7fb-457745e2d3da.png)

### Platform Description

Windows 10 22H2, RTX 3090

**Comment by mart-hill** [comment]
For now, I'm using such settings, while the Tiled VAE works:
![image](https://user-images.githubusercontent.com/55754730/232114927-0ba52b05-25d2-4fc1-822a-b44d2a234b86.png)

As I mentioned, if/when I switch to SDP and reload the model (which requires me to switch to another, then return to the one I've used), Tiled VAE will still work unless I fully "reboot" the UI. 

By the way, could changing of the "Cross-attention optimization method" include a complete reload of the current model? I know, it'll take more time for saving the config, but it'll probably necessary for the selected CAOM to "kick in", right? Well, excluding xformers, which, apparently, requires full restart of the UI.

**Comment by vladmandic** [comment]
> By the way, could changing of the "Cross-attention optimization method" include a complete reload of the current model?

It could, but its non-trivial, likely going to cause at least some issues and would be veeery rarely used.
99% of users may experiment with different cross-atention methods in early days and then just stick with one, I don't see a reason to support changing it on-the-fly.

**Comment by vladmandic** [comment]
this is issue with the extension, should be a very simple fix, but its up to that author to do it.
tracking under <https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/130>

**Comment by pkuliyi2015** [comment]
Hello, I make a trial fix in the dev branch but I can't have a test as I don't use sdp or torch 2.0 currently. My environment is shared by so many other projects that I can't make a switch.

Would you mind have a test? If it works I merge it into the main branch.

**Comment by mart-hill** [comment]
Now, I've noticed, that now Tiled VAE does indeed work with SDP optimizations (thank you!), but **not** with xformers. I'll switch then! 🙂 

```
100%|██████████████████████████████████████████████████████████████████████████████| 60/60 [00:08<00:00,  7.10it/s]
[Tiled VAE]: the input size is tiny and unnecessary to tile.
[Tiled VAE]: input_size: torch.Size([1, 3, 1531, 1072]), tile_size: 256, padding: 32
[Tiled VAE]: split to 6x4 = 24 tiles. Optimal tile size 256x256, original tile size 256x256
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 179 x 256 image
[Tiled VAE]: Executing Encoder Task Queue:  82%|███████████████████████▋     | 1787/2184 [00:03<00:00, 1006.17it/s]gradio call: AttributeError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ X:\AI\automatic\modules\call_queue.py:59 in f                                                                    │
│                                                                                                                  │
│    58 │   │   │   │   pr.enable()                                                                                │
│ ❱  59 │   │   │   res = list(func(*args, **kwargs))                                                              │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                    │
│                                                                                                                  │
│ X:\AI\automatic\modules\call_queue.py:38 in f                                                                    │
│                                                                                                                  │
│    37 │   │   │   try:                                                                                           │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                │
│    39 │   │   │   finally:                                                                                       │
│                                                                                                                  │
│                                             ... 16 frames hidden ...                                             │
│                                                                                                                  │
│ X:\AI\automatic\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\attn.py:91 in                    │
│ xformers_attnblock_forward                                                                                       │
│                                                                                                                  │
│    90 │   │   v = v.contiguous()                                                                                 │
│ ❱  91 │   │   out = xformers.ops.memory_efficient_attention(q, k, v, op=get_xformers_flash_att                   │
│    92 │   │   out = out.to(dtype)                                                                                │
│                                                                                                                  │
│ X:\AI\automatic\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\attn.py:230 in                   │
│ get_xformers_flash_attention_op                                                                                  │
│                                                                                                                  │
│   229 def get_xformers_flash_attention_op(q, k, v):                                                              │
│ ❱ 230 │   if not shared.cmd_opts.xformers_flash_attention:                                                       │
│   231 │   │   return None                                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'xformers_flash_attention'
```

**Comment by CapsAdmin** [comment]
> > By the way, could changing of the "Cross-attention optimization method" include a complete reload of the current model?
> 
> It could, but its non-trivial, likely going to cause at least some issues and would be veeery rarely used. 99% of users may experiment with different cross-atention methods in early days and then just stick with one, I don't see a reason to support changing it on-the-fly.


Locally I made something that let me change it on the fly and I kinda found it useful. Sometimes I switch to sub quad attention if I want to generate something high resolution to avoid OOM. And some 2.1 768 models on AMD produce black images when using half precision on certain cross attention methods while others work.

**Comment by pkuliyi2015** [comment]
> I've noticed, that Tiled VAE does indeed work with SDP optimizations now (thank you!), but **not** with xformers. I'll switch then! 🙂
> 
> The error appears, when I'm on xformers:
> 
> ```
> 100%|██████████████████████████████████████████████████████████████████████████████| 60/60 [00:08<00:00,  7.10it/s]
> [Tiled VAE]: the input size is tiny and unnecessary to tile.
> [Tiled VAE]: input_size: torch.Size([1, 3, 1531, 1072]), tile_size: 256, padding: 32
> [Tiled VAE]: split to 6x4 = 24 tiles. Optimal tile size 256x256, original tile size 256x256
> [Tiled VAE]: Fast mode enabled, estimating group norm parameters on 179 x 256 image
> [Tiled VAE]: Executing Encoder Task Queue:  82%|███████████████████████▋     | 1787/2184 [00:03<00:00, 1006.17it/s]gradio call: AttributeError
> ╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
> │ X:\AI\automatic\modules\call_queue.py:59 in f                                                                    │
> │                                                                                                                  │
> │    58 │   │   │   │   pr.enable()                                                                                │
> │ ❱  59 │   │   │   res = list(func(*args, **kwargs))                                                              │
> │    60 │   │   │   if shared.cmd_opts.profile:                                                                    │
> │                                                                                                                  │
> │ X:\AI\automatic\modules\call_queue.py:38 in f                                                                    │
> │                                                                                                                  │
> │    37 │   │   │   try:                                                                                           │
> │ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                │
> │    39 │   │   │   finally:                                                                                       │
> │                                                                                                                  │
> │                                             ... 16 frames hidden ...                                             │
> │                                                                                                                  │
> │ X:\AI\automatic\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\attn.py:91 in                    │
> │ xformers_attnblock_forward                                                                                       │
> │                                                                                                                  │
> │    90 │   │   v = v.contiguous()                                                                                 │
> │ ❱  91 │   │   out = xformers.ops.memory_efficient_attention(q, k, v, op=get_xformers_flash_att                   │
> │    92 │   │   out = out.to(dtype)                                                                                │
> │                                                                                                                  │
> │ X:\AI\automatic\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\attn.py:230 in                   │
> │ get_xformers_flash_attention_op                                                                                  │
> │                                                                                                                  │
> │   229 def get_xformers_flash_attention_op(q, k, v):                                                              │
> │ ❱ 230 │   if not shared.cmd_opts.xformers_flash_attention:                                                       │
> │   231 │   │   return None                                                                                        │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> AttributeError: 'Namespace' object has no attribute 'xformers_flash_attention'
> ```

The vlad's repo changed the options here:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/59076257/232242258-4ea6421d-c3c5-4744-bb8e-f4498a5f2be7.png">

But in automatic it is like this:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/59076257/232242343-111b3e04-60d0-4bc4-93a7-857ee02a132e.png">

I think I found a tricky solution, i.e., just import their functions, as I don't need to change the code inside. I will efficiently fix the errors.

**Comment by pkuliyi2015** [comment]
> I've noticed, that Tiled VAE does indeed work with SDP optimizations now (thank you!), but **not** with xformers. I'll switch then! 🙂
> 
> The error appears, when I'm on xformers:
> 
> ```
> 100%|██████████████████████████████████████████████████████████████████████████████| 60/60 [00:08<00:00,  7.10it/s]
> [Tiled VAE]: the input size is tiny and unnecessary to tile.
> [Tiled VAE]: input_size: torch.Size([1, 3, 1531, 1072]), tile_size: 256, padding: 32
> [Tiled VAE]: split to 6x4 = 24 tiles. Optimal tile size 256x256, original tile size 256x256
> [Tiled VAE]: Fast mode enabled, estimating group norm parameters on 179 x 256 image
> [Tiled VAE]: Executing Encoder Task Queue:  82%|███████████████████████▋     | 1787/2184 [00:03<00:00, 1006.17it/s]gradio call: AttributeError
> ╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
> │ X:\AI\automatic\modules\call_queue.py:59 in f                                                                    │
> │                                                                                                                  │
> │    58 │   │   │   │   pr.enable()                                                                                │
> │ ❱  59 │   │   │   res = list(func(*args, **kwargs))                                                              │
> │    60 │   │   │   if shared.cmd_opts.profile:                                                                    │
> │                                                                                                                  │
> │ X:\AI\automatic\modules\call_queue.py:38 in f                                                                    │
> │                                                                                                                  │
> │    37 │   │   │   try:                                                                                           │
> │ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                │
> │    39 │   │   │   finally:                                                                                       │
> │                                                                                                                  │
> │                                             ... 16 frames hidden ...                                             │
> │                                                                                                                  │
> │ X:\AI\automatic\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\attn.py:91 in                    │
> │ xformers_attnblock_forward                                                                                       │
> │                                                                                                                  │
> │    90 │   │   v = v.contiguous()                                                                                 │
> │ ❱  91 │   │   out = xformers.ops.memory_efficient_attention(q, k, v, op=get_xformers_flash_att                   │
> │    92 │   │   out = out.to(dtype)                                                                                │
> │                                                                                                                  │
> │ X:\AI\automatic\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\attn.py:230 in                   │
> │ get_xformers_flash_attention_op                                                                                  │
> │                                                                                                                  │
> │   229 def get_xformers_flash_attention_op(q, k, v):                                                              │
> │ ❱ 230 │   if not shared.cmd_opts.xformers_flash_attention:                                                       │
> │   231 │   │   return None                                                                                        │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> AttributeError: 'Namespace' object has no attribute 'xformers_flash_attention'
> ```

Ok it should work now. Would you mind having another try? @CapsAdmin

**Comment by mart-hill** [comment]
Thank you! Trying. 🙂

**Comment by pkuliyi2015** [comment]
Yes should be irrelevant. If something goes wrong you should see the errors about Tiled VAE.

**Comment by mart-hill** [comment]
Hmm, with latest UI commit, 492a747, I still don't see Tiled VAE or Multidiffusion parts of the UI:
![obraz](https://user-images.githubusercontent.com/55754730/232245634-079f9f27-0b92-488a-ad9c-93a3b23a4d0b.png)

**Comment by CapsAdmin** [comment]
> 

Is the multidiffusion directory empty? if so try `git submodule update --init` in cmd while in the automatic repo

**Comment by pkuliyi2015** [comment]
This seems to be a git cache error. You may remove my extension in the folder and install again.

**Comment by mart-hill** [comment]
I just updated it with git -pull inside your extension's directory, I'll run the UI again!

**Comment by pkuliyi2015** [comment]
The git cache problem is usually annoying...

**Comment by mart-hill** [comment]
It is, but your extension appeared back! 🙂 
Trying to generate something with T-VAE on and xformers!

**Comment by mart-hill** [comment]
Drat, it still errors:

```
100%|██████████████████████████████████████████████████████████████████████████████| 60/60 [00:08<00:00,  6.70it/s]
[Tiled VAE]: the input size is tiny and unnecessary to tile.
[Tiled VAE]: input_size: torch.Size([1, 3, 3428, 2400]), tile_size: 256, padding: 32
[Tiled VAE]: split to 14x10 = 140 tiles. Optimal tile size 256x256, original tile size 256x256
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 179 x 255 image
[Tiled VAE]: Executing Encoder Task Queue:  83%|██████████████████████▌    | 10631/12740 [00:13<00:01, 1686.35it/s]gradio call: AttributeError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ X:\AI\automatic\modules\call_queue.py:59 in f                                                                    │
│                                                                                                                  │
│    58 │   │   │   │   pr.enable()                                                                                │
│ ❱  59 │   │   │   res = list(func(*args, **kwargs))                                                              │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                    │
│                                                                                                                  │
│ X:\AI\automatic\modules\call_queue.py:38 in f                                                                    │
│                                                                                                                  │
│    37 │   │   │   try:                                                                                           │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                │
│    39 │   │   │   finally:                                                                                       │
│                                                                                                                  │
│                                             ... 16 frames hidden ...                                             │
│                                                                                                                  │
│ X:\AI\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\tile_utils\attn.py:91 in            │
│ xformers_attnblock_forward                                                                                       │
│                                                                                                                  │
│    90 │   │   v = v.contiguous()                                                                                 │
│ ❱  91 │   │   out = xformers.ops.memory_efficient_attention(q, k, v, op=get_xformers_flash_att                   │
│    92 │   │   out = out.to(dtype)                                                                                │
│                                                                                                                  │
│ X:\AI\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\tile_utils\attn.py:230 in           │
│ get_xformers_flash_attention_op                                                                                  │
│                                                                                                                  │
│   229 def get_xformers_flash_attention_op(q, k, v):                                                              │
│ ❱ 230 │   if not shared.cmd_opts.xformers_flash_attention:                                                       │
│   231 │   │   return None                                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'xformers_flash_attention'
```

Should I reboot the OS  (python cache in the venv)?

**Comment by pkuliyi2015** [comment]
Oh please switch to the main branch. I'm sorry that I didn't push on the dev branch.

**Comment by mart-hill** [comment]
Oh, okay!

**Comment by mart-hill** [comment]
Switched and checked on SDP optimization - works! I'm using --no-half-vae option and "Enable upcast sampling. Usually produces similar results to --no-half with better performance while using less memory" options though.🙂 

Now going to restart the UI with xformers!

**Comment by pkuliyi2015** [comment]
Looking forward to your results!

**Comment by mart-hill** [comment]
It works now, thank you very much for your efforts! 🙂 
I still need to read, how to actually use your extension to upscale images though! :)

**Comment by pkuliyi2015** [comment]
You are welcome. There is a tutorial on Civitai website, namely, https://civitai.com/models/34726/tutorial-for-multidiffusion-upscaler-for-automatic1111-detail-to-the-max

**Comment by mart-hill** [comment]
The bug with Tiled VAE returned in a bit different form:
```
100%|██████████████████████████████████████████████████████████████████████████████| 40/40 [00:06<00:00,  5.91it/s]
[Tiled VAE]: the input size is tiny and unnecessary to tile.
[Tiled VAE]: input_size: torch.Size([1, 3, 1544, 982]), tile_size: 256, padding: 32
[Tiled VAE]: split to 6x4 = 24 tiles. Optimal tile size 256x256, original tile size 256x256
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 162 x 256 image
[Tiled VAE]: Executing Encoder Task Queue: 100%|██████████████████████████████| 2184/2184 [00:02<00:00, 995.90it/s]
[Tiled VAE]: Done in 2.940s, max VRAM alloc 3857.145 MB
gradio call: RuntimeError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ X:\AI\automatic\modules\call_queue.py:61 in f                                                                    │
│                                                                                                                  │
│    60 │   │   │   │   pr.enable()                                                                                │
│ ❱  61 │   │   │   res = list(func(*args, **kwargs))                                                              │
│    62 │   │   │   if shared.cmd_opts.profile:                                                                    │
│                                                                                                                  │
│ X:\AI\automatic\modules\call_queue.py:39 in f                                                                    │
│                                                                                                                  │
│    38 │   │   │   try:                                                                                           │
│ ❱  39 │   │   │   │   res = func(*args, **kwargs)                                                                │
│    40 │   │   │   finally:                                                                                       │
│                                                                                                                  │
│                                             ... 13 frames hidden ...                                             │
│                                                                                                                  │
│ X:\AI\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                                   │
│                                                                                                                  │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                           │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                          │
│    464                                                                                                           │
│                                                                                                                  │
│ X:\AI\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                             │
│                                                                                                                  │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                         │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                 │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same
```
This happens, when I have Tiled VAE on and with 256px tile size, with foolhardy_remacri upscaler (to force the script do its work).

Also, the image generation suddenly became very touchy with NaN:
```
100%|██████████████████████████████████████████████████████████████████████████████| 40/40 [00:06<00:00,  5.82it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 40/40 [00:28<00:00,  1.41it/s]
gradio call: NansException
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ X:\AI\automatic\modules\call_queue.py:61 in f                                                                    │
│    60 │   │   │   │   pr.enable()                                                                                │
│ ❱  61 │   │   │   res = list(func(*args, **kwargs))                                                              │
│    62 │   │   │   if shared.cmd_opts.profile:                                                                    │
│                                                                                                                  │
│ X:\AI\automatic\modules\call_queue.py:39 in f                                                                    │
│                                                                                                                  │
│    38 │   │   │   try:                                                                                           │
│ ❱  39 │   │   │   │   res = func(*args, **kwargs)                                                                │
│    40 │   │   │   finally:                                                                                       │
│                                                                                                                  │
│                                             ... 2 frames hidden ...                                              │
│                                                                                                                  │
│ X:\AI\automatic\modules\processing.py:664 in process_images_inner                                                │
│                                                                                                                  │
│    663 │   │   │   for x in x_samples_ddim:                                                                      │
│ ❱  664 │   │   │   │   devices.test_for_nans(x, "vae")                                                           │
│    665                                                                                                           │
│                                                                                                                  │
│ X:\AI\automatic\modules\devices.py:146 in test_for_nans                                                          │
│                                                                                                                  │
│   145 │   message += " Use --disable-nan-check commandline argument to disable this check."                      │
│ ❱ 146 │   raise NansException(message)                                                                           │
│   147                                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
NansException: A tensor with all NaNs was produced in VAE. Use --disable-nan-check commandline argument to disable
this check.
```
I had xformers enabled, and CUDA section was like this:
![image](https://user-images.githubusercontent.com/55754730/233503913-5fbc32b0-1091-4898-b338-4212c58eaf3c.png)
My Stable Diffusion section has this checked:
![image](https://user-images.githubusercontent.com/55754730/233504536-ac0581d5-98fd-4eab-b354-0bef677a0098.png)
I've never had the NaN values problem before while using the typical --no-half-vae with your fork or vanilla UI while having Torch 2.0 with these settings, until now.


There's also a problem with initialization of Additional Networks extension:
```
Module load: X:\AI\automatic\extensions\sd-webui-additional-networks\scripts\additional_networks.py: AttributeError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ X:\AI\automatic\modules\script_loading.py:10 in load_module                                                      │
│                                                                                                                  │
│    9 │   try:                                                                                                    │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                              │
│   11 │   except Exception as e:                                                                                  │
│ in exec_module:883                                                                                               │
│ in _call_with_frames_removed:241                                                                                 │
│                                                                                                                  │
│ X:\AI\automatic\extensions\sd-webui-additional-networks\scripts\additional_networks.py:392 in <module>           │
│                                                                                                                  │
│   391                                                                                                            │
│ ❱ 392 xyz_grid_support.initialize(Script)                                                                        │
│   393                                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'scripts.xyz_grid_support' has no attribute 'initialize'
```
The extension partially works during using ↙️ button, it accepts LoRAS used before, but sets ALL sliders to 1, even with the empty "Network module n" ones.

Sorry, that I gathered all observations within this issue, but I didn't want to make a mess. 🙂 

Windows 22H2, RTX 3090
Version: df424d6d Thu Apr 20 17:18:31 2023 -0400

**Comment by mart-hill** [comment]
The issue with Tiled VAE at this point can be resolved with [these CUDA settings](https://github.com/vladmandic/automatic/issues/345#issuecomment-1518108325). NaN stuff - TBD. 🙂
