### ISSUE TITLE
[Issue]: task_scheduler.py causing AttributeError on startup

### ISSUE THREAD

**Issue by solsol360** [vladmandic/automatic#1281]
### Issue Description

Hi,
task_scheduler.py gives some errors on startup after updating. Image generation still seems to work. Also the new queue seems to work (as far as I know). 

DEBUG log:

```log
Please fill this form with as much information as possible
08:40:12-761806 INFO     Running extension preloading
08:40:12-774262 INFO     Starting SD.Next
08:40:12-775750 INFO     Python 3.10.9 on Windows
08:40:12-823365 INFO     Version: 299f1229 Fri Jun 2 20:54:09 2023 -0400
08:40:13-300925 INFO     Setting environment tuning
08:40:13-302925 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False
08:40:13-305407 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True
08:40:13-308383 INFO     nVidia CUDA toolkit detected
08:40:13-309871 DEBUG    Package version found: torch 2.0.1+cu118
08:40:13-311359 DEBUG    Package version found: torchvision 0.15.2+cu118
08:40:15-118031 INFO     Torch 2.0.1+cu118
08:40:15-137399 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
08:40:15-139383 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10239 Arch (8, 6) Cores 68
08:40:15-141864 DEBUG    Package version found: tensorflow 2.12.0
08:40:15-143352 INFO     Verifying requirements
08:40:15-144854 DEBUG    Package version found: addict 2.4.0
08:40:15-146327 DEBUG    Package version found: aenum 3.1.12
08:40:15-148313 DEBUG    Package version found: aiohttp 3.8.4
08:40:15-149784 DEBUG    Package version found: anyio 3.6.2
08:40:15-151288 DEBUG    Package version found: appdirs 1.4.4
08:40:15-152775 DEBUG    Package version found: astunparse 1.6.3
08:40:15-154264 DEBUG    Package version found: bitsandbytes 0.38.1
08:40:15-155752 DEBUG    Package version found: blendmodes 2022
08:40:15-157241 DEBUG    Package version found: clean-fid 0.1.35
08:40:15-158733 DEBUG    Package version found: easydev 0.12.1
08:40:15-161679 DEBUG    Package version found: extcolors 1.0.0
08:40:15-163167 DEBUG    Package version found: facexlib 0.3.0
08:40:15-164680 DEBUG    Package version found: filetype 1.2.0
08:40:15-166167 DEBUG    Package version found: font-roboto 0.0.1
08:40:15-168151 DEBUG    Package version found: fonts 0.0.3
08:40:15-169639 DEBUG    Package version found: future 0.18.3
08:40:15-171127 DEBUG    Package version found: gdown 4.7.1
08:40:15-172615 DEBUG    Package version found: gfpgan 1.3.8
08:40:15-174103 DEBUG    Package version found: GitPython 3.1.31
08:40:15-177054 DEBUG    Package version found: httpcore 0.17.0
08:40:15-178571 DEBUG    Package version found: inflection 0.5.1
08:40:15-180527 DEBUG    Package version found: jsonmerge 1.9.0
08:40:15-182039 DEBUG    Package version found: kornia 0.6.12
08:40:15-183529 DEBUG    Package version found: lark 1.1.5
08:40:15-185015 DEBUG    Package version found: lmdb 1.4.1
08:40:15-186999 DEBUG    Package version found: lpips 0.1.4
08:40:15-188488 DEBUG    Package version found: omegaconf 2.3.0
08:40:15-189974 DEBUG    Package version found: open-clip-torch 2.18.0
08:40:15-191970 DEBUG    Package version found: opencv-contrib-python 4.7.0.72
08:40:15-193447 DEBUG    Package version found: piexif 1.1.3
08:40:15-195431 DEBUG    Package version found: Pillow 9.5.0
08:40:15-196895 DEBUG    Package version found: psutil 5.9.5
08:40:15-198410 DEBUG    Package version found: pyyaml 6.0
08:40:15-199896 DEBUG    Package version found: realesrgan 0.3.0
08:40:15-201387 DEBUG    Package version found: resize-right 0.0.2
08:40:15-203368 DEBUG    Package version found: rich 13.3.5
08:40:15-204854 DEBUG    Package version found: safetensors 0.3.1
08:40:15-207311 DEBUG    Package version found: scipy 1.10.1
08:40:15-208825 DEBUG    Package version found: tb_nightly 2.13.0a20230501
08:40:15-210311 DEBUG    Package version found: toml 0.10.2
08:40:15-211798 DEBUG    Package version found: torchdiffeq 0.2.3
08:40:15-213287 DEBUG    Package version found: torchsde 0.2.5
08:40:15-214775 DEBUG    Package version found: voluptuous 0.13.1
08:40:15-216263 DEBUG    Package version found: yapf 0.33.0
08:40:15-218249 DEBUG    Package version found: scikit-image 0.19.2
08:40:15-219736 DEBUG    Package version found: basicsr 1.4.2
08:40:15-221223 DEBUG    Package version found: compel 1.1.5
08:40:15-224199 DEBUG    Package version found: requests 2.31.0
08:40:15-226159 DEBUG    Package version found: tqdm 4.65.0
08:40:15-227671 DEBUG    Package version found: accelerate 0.18.0
08:40:15-229159 DEBUG    Package version found: opencv-python 4.7.0.72
08:40:15-230650 DEBUG    Package version found: diffusers 0.16.1
08:40:15-232135 DEBUG    Package version found: einops 0.4.1
08:40:15-233627 DEBUG    Package version found: gradio 3.32.0
08:40:15-235087 DEBUG    Package version found: numexpr 2.8.4
08:40:15-238559 DEBUG    Package version found: numpy 1.23.5
08:40:15-240071 DEBUG    Package version found: numba 0.57.0
08:40:15-241560 DEBUG    Package version found: pandas 1.5.3
08:40:15-243047 DEBUG    Package version found: protobuf 3.20.3
08:40:15-244546 DEBUG    Package version found: pytorch_lightning 1.9.4
08:40:15-246519 DEBUG    Package version found: transformers 4.26.1
08:40:15-248007 DEBUG    Package version found: timm 0.6.13
08:40:15-249495 DEBUG    Package version found: tomesd 0.1.2
08:40:15-250962 DEBUG    Package version found: urllib3 1.26.15
08:40:15-253464 INFO     Installing packages
08:40:15-254955 DEBUG    Package version found: clip 1.0
08:40:15-256440 DEBUG    Package version found: onnxruntime 1.14.0
08:40:15-305410 DEBUG    Repository update time: Sat Jun  3 03:54:09 2023
08:40:15-307395 DEBUG    Previous setup time: Sat Jun  3 08:36:48 2023
08:40:15-310398 DEBUG    Extension version: Fri Jun  2 16:20:32 2023
                         D:\automatic\extensions-builtin;a1111-sd-webui-lycoris
08:40:15-312878 DEBUG    Extension version: Wed May 24 17:47:38 2023
                         D:\automatic\extensions-builtin;clip-interrogator-ext
08:40:15-315360 DEBUG    Extension version: Wed May 31 07:33:00 2023 D:\automatic\extensions-builtin;LDSR
08:40:15-317342 DEBUG    Extension version: Wed May 31 07:33:00 2023 D:\automatic\extensions-builtin;Lora
08:40:15-319822 DEBUG    Extension version: Sun May 28 17:04:04 2023
                         D:\automatic\extensions-builtin;multidiffusion-upscaler-for-automatic1111
08:40:15-322302 DEBUG    Extension version: Wed May 31 07:33:00 2023 D:\automatic\extensions-builtin;ScuNET
08:40:15-324754 DEBUG    Extension version: Mon May 22 22:32:16 2023
                         D:\automatic\extensions-builtin;sd-dynamic-thresholding
08:40:15-327807 DEBUG    Extension version: Sun May 21 22:20:46 2023
                         D:\automatic\extensions-builtin;sd-extension-aesthetic-scorer
08:40:15-331775 DEBUG    Extension version: Sun May 21 22:20:47 2023
                         D:\automatic\extensions-builtin;sd-extension-steps-animation
08:40:15-335247 DEBUG    Extension version: Fri Jun  2 16:20:35 2023
                         D:\automatic\extensions-builtin;sd-extension-system-info
08:40:15-338223 DEBUG    Extension version: Sat Jun  3 08:34:54 2023
                         D:\automatic\extensions-builtin;sd-webui-agent-scheduler
08:40:15-341199 DEBUG    Extension version: Sat Jun  3 08:36:04 2023
                         D:\automatic\extensions-builtin;sd-webui-controlnet
08:40:15-343679 DEBUG    Extension version: Tue May 23 22:21:32 2023
                         D:\automatic\extensions-builtin;sd-webui-model-converter
08:40:15-347647 DEBUG    Extension version: Wed May 24 17:47:55 2023 D:\automatic\extensions-builtin;seed_travel
08:40:15-350127 DEBUG    Extension version: Fri Jun  2 16:20:37 2023
                         D:\automatic\extensions-builtin;stable-diffusion-webui-images-browser
08:40:15-352607 DEBUG    Extension version: Wed May 24 17:47:59 2023
                         D:\automatic\extensions-builtin;stable-diffusion-webui-rembg
08:40:15-355087 DEBUG    Extension version: Wed May 31 07:33:00 2023 D:\automatic\extensions-builtin;SwinIR
08:40:15-357567 DEBUG    Extension version: Sat Jun  3 08:36:39 2023 D:\automatic\extensions;canvas-zoom
08:40:15-360047 DEBUG    Extension version: Sat Jun  3 08:36:43 2023 D:\automatic\extensions;SD-CN-Animation
08:40:15-362527 DEBUG    Extension version: Sat Jun  3 08:36:45 2023
                         D:\automatic\extensions;sd-webui-aspect-ratio-helper
08:40:15-365253 DEBUG    Extension version: Sat Jun  3 08:36:46 2023
                         D:\automatic\extensions;ultimate-upscale-for-automatic1111
08:40:15-367236 DEBUG    Latest extensions time: Sat Jun  3 08:36:46 2023
08:40:15-368690 DEBUG    Timestamps: version:1685753649 setup:1685770608 extension:1685770606
08:40:15-370164 INFO     No changes detected: Quick launch active
08:40:15-371167 INFO     Running extension preloading
08:40:15-372660 INFO     Server arguments: ['--debug']
08:40:15-374145 DEBUG    Starting WebUI
08:40:15-388579 DEBUG    Memory used: 0.33 total: 31.92 Collected 0
No module 'xformers'. Proceeding without it.
08:40:23-256540 INFO     Libraries loaded
08:40:23-260508 DEBUG    Entering start sequence
08:40:23-383584 DEBUG    Version: {'app': 'sd.next', 'updated': '2023-06-02', 'hash': '299f1229', 'url':
                         'https://github.com/vladmandic/automatic/tree/master'}
08:40:23-387028 INFO     Using data path: D:\automatic
08:40:23-389012 DEBUG    Entering Initialize
08:40:23-393475 INFO     Available VAEs: D:\automatic\models\VAE 2
08:40:23-420388 INFO     Available models: D:\automatic\models\Stable-diffusion 12
ControlNet v1.1.214
ControlNet v1.1.214
08:40:28-608966 INFO     Libraries loaded
08:40:28-931484 INFO     Loading UI theme: name=gradio/default style=Auto
08:40:28-935929 DEBUG    Creating UI
08:40:28-951305 DEBUG    Adding JS scripts: ['/javascript/aspectRatioOverlay.js', '/javascript/contextMenus.js',
                         '/javascript/dragdrop.js', '/javascript/edit-attention.js', '/javascript/extensions.js',
                         '/javascript/extraNetworks.js', '/javascript/generationParams.js', '/javascript/hints.js',
                         '/javascript/hires.js', '/javascript/imageMaskFix.js', '/javascript/imageParams.js',
                         '/javascript/imageviewer.js', '/javascript/notification.js', '/javascript/progressbar.js',
                         '/javascript/prompt-bracket-checker.js', '/javascript/set-hints.js',
                         '/javascript/textualInversion.js', '/javascript/ui.js',
                         '/extensions-builtin/multidiffusion-upscaler-for-automatic1111/javascript/bboxHint.js',
                         '/extensions-builtin/sd-extension-system-info/javascript/jquery.js',
                         '/extensions-builtin/sd-extension-system-info/javascript/sparkline.js',
                         '/extensions-builtin/sd-extension-system-info/javascript/system-info.js',
                         '/extensions-builtin/sd-webui-controlnet/javascript/hints.js',
                         '/extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js',
                         '/extensions/canvas-zoom/javascript/canvas-zoom.js',
                         '/extensions/canvas-zoom/javascript/customHotkeys.js',
                         '/extensions/sd-webui-aspect-ratio-helper/javascript/aspectRatioController.js',
                         '/extensions-builtin/sd-webui-agent-scheduler/javascript/extension.mjs']
08:40:28-968104 DEBUG    Adding CSS stylesheets: ['javascript/style.css',
                         '/extensions-builtin/sd-webui-agent-scheduler/style.css',
                         '/extensions-builtin/stable-diffusion-webui-images-browser/style.css',
                         '/extensions/canvas-zoom/style.css', '/extensions/sd-webui-aspect-ratio-helper/style.css']
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
08:40:30-361377 DEBUG    Extensions list loaded: D:\automatic\html\extensions.json
08:40:32-401231 DEBUG    Extensions manager: refresh list search="" sort="default"
08:40:32-446981 DEBUG    Select checkpoint: edgeOfRealism_eorV20Fp16BakedVAE.safetensors [7f6146b8a9]
08:40:32-449568 DEBUG    Load model:
                         name=D:\automatic\models\Stable-diffusion\edgeOfRealism_eorV20Fp16BakedVAE.safetensors
                         dict=False
08:40:32-452073 DEBUG    Verifying Torch settings
08:40:32-495824 DEBUG    Torch FP16 test passed
08:40:32-497808 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False
08:40:32-499769 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
08:40:32-501257 DEBUG    Torch default device: cuda
Loading weights: D:\automatic\models\Stable-diffusion\edgeOfRealism_eorV20Fp16BakedVAE.safetensors ------ 0.0/2… -:--:…
                                                                                                          GB
08:40:32-699161 DEBUG    Model dict loaded: {'ram': {'used': 0.98, 'total': 31.92}, 'gpu': {'used': 1.16, 'total':
                         10.0}, 'retries': 0, 'oom': 0}
08:40:32-714568 DEBUG    Model config loaded: {'ram': {'used': 0.98, 'total': 31.92}, 'gpu': {'used': 1.16, 'total':
                         10.0}, 'retries': 0, 'oom': 0}
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
08:40:33-082482 INFO     Model created from config: D:\automatic\configs\v1-inference.yaml
08:40:33-084976 DEBUG    Model weights loading: {'ram': {'used': 1.95, 'total': 31.92}, 'gpu': {'used': 1.16, 'total':
                         10.0}, 'retries': 0, 'oom': 0}
08:40:33-942558 DEBUG    Model weights loaded: {'ram': {'used': 4.99, 'total': 31.92}, 'gpu': {'used': 1.16, 'total':
                         10.0}, 'retries': 0, 'oom': 0}
08:40:34-666250 DEBUG    Model weights moved: {'ram': {'used': 3.0, 'total': 31.92}, 'gpu': {'used': 3.19, 'total':
                         10.0}, 'retries': 0, 'oom': 0}
08:40:34-677132 INFO     Applying scaled dot product cross attention optimization
08:40:34-760124 INFO     Model loaded in 2.3s (load=0.2s create=0.4s apply=0.4s vae=0.5s move=0.7s embeddings=0.1s)
08:40:34-931739 DEBUG    gc: collected=2893 device=cuda {'ram': {'used': 3.04, 'total': 31.92}, 'gpu': {'used': 3.19,
                         'total': 10.0}, 'retries': 0, 'oom': 0}
08:40:34-937244 INFO     Model load finished: {'ram': {'used': 3.04, 'total': 31.92}, 'gpu': {'used': 3.19, 'total':
                         10.0}, 'retries': 0, 'oom': 0}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
08:40:35-606122 INFO     Local URL: http://127.0.0.1:7860/
08:40:35-608079 INFO     API Docs: http://127.0.0.1:7860/docs
08:40:35-609095 DEBUG    Gradio registered functions: 1507
08:40:35-610087 INFO     Initializing middleware
08:40:35-615543 DEBUG    Creating API
08:40:35-784765 INFO     [AgentScheduler] Registering APIs
08:40:35-797164 INFO     [AgentScheduler] Task queue is empty
Create LRU cache (max_size=16) for preprocessor results.
08:40:36-015404 ERROR    executing callback:
                         D:\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py
                         app_started_callback: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\script_callbacks.py:125 in app_started_callback                                                │
│                                                                                                                     │
│   124 │   │   try:                                                                                                  │
│ > 125 │   │   │   c.callback(demo, app)                                                                             │
│   126 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ D:\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:24 in <lambda>                   │
│                                                                                                                     │
│    23 │   │   super().__init__()                                                                                    │
│ >  24 │   │   script_callbacks.on_app_started(lambda block, _: self.on_app_started(block))                          │
│    25 │   │   self.checkpoint_override = checkpoint_current                                                         │
│                                                                                                                     │
│ D:\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:43 in on_app_started             │
│                                                                                                                     │
│    42 │   def on_app_started(self, block):                                                                          │
│ >  43 │   │   self.add_enqueue_button(block, self.generate_button)                                                  │
│    44                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Script' object has no attribute 'generate_button'
08:40:36-269350 DEBUG    gc: collected=17821 device=cuda {'ram': {'used': 1.09, 'total': 31.92}, 'gpu': {'used': 3.19,
                         'total': 10.0}, 'retries': 0, 'oom': 0}
08:40:36-455350 DEBUG    gc: collected=124 device=cuda {'ram': {'used': 1.09, 'total': 31.92}, 'gpu': {'used': 3.19,
                         'total': 10.0}, 'retries': 0, 'oom': 0}
08:40:36-461045 INFO     Startup time: 21.1s (torch=5.0s gradio=0.9s libraries=1.9s vae=0.1s codeformer=0.1s
                         scripts=5.2s onchange=0.1s ui=6.1s launch=0.5s scripts app_started_callback=0.5s
                         checkpoint=0.4s)
```

### Version Platform Description

08:40:12-775750 INFO     Python 3.10.9 on Windows
08:40:12-823365 INFO     Version: 299f1229 Fri Jun 2 20:54:09 2023 -0400
Using Firefox 113.0.2 (64-bit)

**Comment by vladmandic** [comment]
i've tried to reproduce, but no luck.
looking at the code, this can only happen if somehow server started before ui components were fully created.
is this reproducible on your system every time?
can you try starting `webui --debug --safe` to see if some other extensions are perhaps adding too much time to ui creation?

**Comment by solsol360** [comment]
I could repeat this every time. I have only 4 user installed extensions. So I ran the startup with only one extension activated at a time and it seems the culprit is SD-CN-Animation that is causing the error. So extension related issue.


With --debug --safe I don't get the same error, but new one immediately after Creating UI. This error isn't coming if the safe mode is not enabled.


17:53:52-622361 DEBUG    Creating UI
17:53:52-624980 ERROR    executing callback:
                         D:\automatic\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py before_ui:
                         AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\script_callbacks.py:257 in before_ui_callback                                                  │
│                                                                                                                     │
│   256 │   │   try:                                                                                                  │
│ > 257 │   │   │   c.callback()                                                                                      │
│   258 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ D:\automatic\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py:20 in before_ui                    │
│                                                                                                                     │
│   19 def before_ui():                                                                                               │
│ > 20 │   if shared.cmd_opts.lyco_patch_lora:                                                                        │
│   21 │   │   print(                                                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'lyco_patch_lora'

**Comment by vladmandic** [comment]
regarding `lyco_patch_lora`, error is due to chicken-or-the-egg scenario: newly introduced cmdline param is parsed before its registered. and that happens only on initial update of the extension where param is introduced. any subsequent starts should be clean.
i need to think how to reorg the sequence of code so this what-comes-first does not happen

but that has nothing to do with original issue you've reported: `AttributeError: 'Script' object has no attribute 'generate_button'`
seems you found the culprit - `sd-cn-animation` is taking waaay too much time to initialize and server startup sequence already finished. i'll give that some thought as well.

**Comment by vladmandic** [comment]
for `AttributeError: 'Script' object has no attribute 'generate_button'` i've created a pr that should solve it https://github.com/ArtVentureX/sd-webui-agent-scheduler/pull/10

**Comment by vladmandic** [comment]
and i'm about to push the update to fix `AttributeError: 'Namespace' object has no attribute 'lyco_patch_lora'`

**Comment by gsgoldma** [comment]
have this same error

**Comment by vladmandic** [comment]
I'm guessing it's going to be merged on Mon since not many crazy devs are working over the weekend.

**Comment by ConstantEgo** [comment]
sd-webui-agent-scheduler just updated to this:
 #https://github.com/ArtVentureX/sd-webui-agent-scheduler/commit/74a6f73b0637cc7058a571ab3572170f80401c52

but issue is still here
no matter with user extensions is enabled or disabled (empty extensions folder)

`
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\AI\automatic\launch.py:149 in <module>                                                                           │
│                                                                                                                     │
│   148                                                                                                               │
│ > 149     instance = start_server(immediate=True, server=None)                                                      │
│   150     while True:                                                                                               │
│                                                                                                                     │
│ C:\AI\automatic\launch.py:129 in start_server                                                                       │
│                                                                                                                     │
│   128         else:                                                                                                 │
│ > 129             server = server.webui()                                                                           │
│   130     if args.profile:                                                                                          │
│                                                                                                                     │
│ C:\AI\automatic\webui.py:276 in webui                                                                               │
│                                                                                                                     │
│   275     start_common()                                                                                            │
│ > 276     start_ui()                                                                                                │
│   277     load_model()                                                                                              │
│                                                                                                                     │
│ C:\AI\automatic\webui.py:204 in start_ui                                                                            │
│                                                                                                                     │
│   203     startup_timer.record("scripts before_ui_callback")                                                        │
│ > 204     shared.demo = modules.ui.create_ui()                                                                      │
│   205     startup_timer.record("ui")                                                                                │
│                                                                                                                     │
│ C:\AI\automatic\modules\ui.py:353 in create_ui                                                                      │
│                                                                                                                     │
│    352     modules.scripts.scripts_current = modules.scripts.scripts_txt2img                                        │
│ >  353     modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)                                     │
│    354     with gr.Blocks(analytics_enabled=False) as txt2img_interface:                                            │
│                                                                                                                     │
│ C:\AI\automatic\modules\scripts.py:282 in initialize_scripts                                                        │
│                                                                                                                     │
│   281         for script_class, path, _basedir, _script_module in auto_processing_scripts + sc                      │
│ > 282             script = script_class()                                                                           │
│   283             script.filename = path                                                                            │
│                                                                                                                     │
│ C:\AI\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:26 in __init__                │
│                                                                                                                     │
│    25         self.checkpoint_override = checkpoint_current                                                         │
│ >  26         self.generate_button                                                                                  │
│    27                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Script' object has no attribute 'generate_button'
`

**Comment by vladmandic** [comment]
typo, just pushed update.

**Comment by fcabanski** [comment]
Is this fixed in the latest update? I just updated, but this error is still happening: AttributeError: 'Script' object has no attribute 'generate_button'

**Comment by Nathan-dm** [comment]
i got same issue after update

**Comment by vladmandic** [comment]
issue is in the extension, but i've just added some exception handling in the main app so it wont prevent app startup

**Comment by vladmandic** [comment]
this is issue has been fixed in the latest update.

**Comment by thebollo** [comment]
I'm seeing this on a brand new fresh install. Log:

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-418-g0f3309eb
Commit hash: 0f3309eb3da7093c74f353fb9e2c1fc779a055c4
D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions-builtin\forge_legacy_preprocessors\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --gradio-allowed-path 'D:\StabilityMatrix-win-x64\Data\Images'
Total VRAM 24563 MB, total RAM 130958 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\models\ControlNetPreprocessor
Using sqlite file: D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-agent-scheduler\task_scheduler.sqlite3
*** Error loading script: task_scheduler.py
    Traceback (most recent call last):
      File "D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 24, in <module>
        from agent_scheduler.task_runner import TaskRunner, get_instance
      File "D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 26, in <module>
        from .db import TaskStatus, Task, task_manager
      File "D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-agent-scheduler\agent_scheduler\db\__init__.py", line 6, in <module>
        from .task import TaskStatus, Task, TaskManager
      File "D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-agent-scheduler\agent_scheduler\db\task.py", line 22, in <module>
        from ..models import TaskModel
      File "D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-agent-scheduler\agent_scheduler\models.py", line 53, in <module>
        class Txt2ImgApiTaskArgs(StableDiffusionTxt2ImgProcessingAPI):
      File "D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-agent-scheduler\agent_scheduler\models.py", line 71, in Txt2ImgApiTaskArgs
        class Config(StableDiffusionTxt2ImgProcessingAPI.__config__):
      File "D:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 237, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__

**Comment by vladmandic** [comment]
this issue is closed for over a year - commenting on it is never a best approach. please create a new issue and document it as needed.
