### ISSUE TITLE
[Feature]: Equal height for extra networks cards and extra networks subdirs

### ISSUE THREAD

**Issue by Ratinod** [vladmandic/automatic#1573]
### Feature description

If you have a lot of folders, then you get a lot of empty space.
Solution: add an option to adjust the overall height of "extra networks" and add a scroll slider for folders.

![before](https://github.com/vladmandic/automatic/assets/12137233/72030e24-ef07-42e1-bfe8-0585e4c489f0)

![after](https://github.com/vladmandic/automatic/assets/12137233/edebc21c-572a-42b3-ba4e-a12ebfec7d23)

### Version Platform Description

dev b216a35
Windows
Firefox

**Comment by vladmandic** [comment]
fixed in dev.
you can test using dev branch or wait until later this week for update to master.

**Comment by Ratinod** [comment]
There is a problem. (again UI collapsed)
![error](https://github.com/vladmandic/automatic/assets/12137233/374fed53-d224-4d12-8c68-916a699bc463)
changing the settings in "Settings -> Extra Networks" doesn't fix it.
And there is no new "extra networks height" setting option. Maybe I'm looking in the wrong place?

**Comment by vladmandic** [comment]
And you're using which branch?

**Comment by Ratinod** [comment]
> And you're using which branch?

git log -n 1 dev
commit 2524b6659c9ee26811f561cfaea610439113a837 (HEAD -> dev, origin/dev)

**Comment by vladmandic** [comment]
regarding folder view width, i've just pushed another update, hopefully this one fixes it.
regarding card height, there is setting -> extra networks -> disable variable aspect ratio

**Comment by Ratinod** [comment]
Problem still exists.

**Comment by Ratinod** [comment]
https://github.com/vladmandic/automatic/assets/12137233/265a3727-1cb2-4aec-af05-9a4c4bdb796d

**Comment by vladmandic** [comment]
because i like to have some sane values. and you seem to know your way around css, so feel free to propose a pr, i don't want to spend back-and-forth until its something you like.

**Comment by Ratinod** [comment]
If I really understood how to do it, I would do it... 
My knowledge of css is that if you change the values, then maybe something will change, or not (for some unknown reason)...
<sub>I'm sorry if I stressed you... I didn't mean anything bad. Just wanted to make sure others don't run into this issue when the changes are pushed to the master branch.</sub>

**Comment by Ratinod** [comment]
> ![error](https://user-images.githubusercontent.com/12137233/250989371-374fed53-d224-4d12-8c68-916a699bc463.png) 

For anyone with the same problem (firefox, 1080p) as in the picture above, create a user.css file in the main folder and add this in there:
```
.extra-network-subdirs { background: var(--input-background-fill); overflow-x: hidden; overflow-y: auto; max-height: 50vh; min-width: 15%; max-width: 120px; }
.extra-networks .custom-button { min-width: 80px; max-width: 100%; width: 100%; background: none; justify-content: left; text-align: left; padding: 2px 8px 2px 8px; box-shadow: none; line-break: anywhere; }
```
