### ISSUE TITLE
[Issue]: Hi-Res Fix is not working correctly for the first image on the batch

### ISSUE THREAD

**Issue by TiagoSantos81** [vladmandic/automatic#1845]
### Issue Description

The first pass is using the same dimensional information -- width and weight -- as the supposed final data, although the correct information is shown in on "Hires resize: from XXX:XXX to XXX:XXX". Obvious effect on first pass processing times and the subject duplication effects.

Might be related to the change in resize_mode parameters in c5b089c.

### Version Platform Description

This occurs on windows platform on the latest updates. Did not happen two days ago.

Version:
app: automatic.git
updated: 2023-07-09
hash: e8c29597

Platform:
rch: AMD64
cpu: AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
system: Windows
python: 3.10.9

 

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
that was fixed, you're using quite an old version.

**Comment by TiagoSantos81** [comment]
> that was fixed, you're using quite an old version.
No, it was updated before the commit you . 
The info I am showing is indeed updated at 09-07-2023 but I had made ```git pull -r``` before writing this ticket. I just had copy pasted without even looking properly at the info, assuming it to be correct.

Did another git pull moments ago, with success, and I still get the same data in the 'System Information' Tab.

![image](https://github.com/vladmandic/automatic/assets/22968614/703c698a-a900-4e49-a88d-401f5c6333da)

This is my 'From Text' Tab:

![image](https://github.com/vladmandic/automatic/assets/22968614/d845a9b6-0048-4eb8-934a-f70e8411ecc4)

As you can see, it contains the most recent layout changes.

So, it seen there is also some but in the system info tab, that is not updating correctly the Version section.

**Comment by TiagoSantos81** [comment]
This issue seems to be related only with the first image in the batch. Repeating the seed in another position of the batch seems to fix it, as shown by both images with seed 705512689, shown below:

Second position in the batch:
![00296-masterpiece extremely intricate fantasy an on old witch](https://github.com/vladmandic/automatic/assets/22968614/c5bf2334-ebb3-460f-8158-130e2e891785)

First position in the batch:
![00299-masterpiece extremely intricate fantasy an on old witch](https://github.com/vladmandic/automatic/assets/22968614/9291240a-65e1-4ae9-b3a9-9f99b38b93da)

**Comment by TiagoSantos81** [comment]
And the grids showing the issue:

Starting on seed 705512688:
![grid-0028-masterpiece extremely intricate fantasy an on old witch](https://github.com/vladmandic/automatic/assets/22968614/1eec28f0-8cc4-41ae-8eab-018b74978f74)

Starting on seed 705512689:
![grid-0030-masterpiece extremely intricate fantasy an on old witch](https://github.com/vladmandic/automatic/assets/22968614/0ec86246-0202-4117-9e7f-8c959eafe8ee)

**Comment by vladmandic** [comment]
ok, i'll reopen. but this may take a while since i have upcoming trip.

**Comment by TiagoSantos81** [comment]
No worries. Thank you for looking into it.

**Comment by StableInfo** [comment]
> This issue seems to be related only with the first image in the batch. Repeating the seed in another position of the batch seems to fix it, as shown by both images with seed 705512689, shown below:
> 
> Second position in the batch: ![00296-masterpiece extremely intricate fantasy an on old witch](https://user-images.githubusercontent.com/22968614/256669450-c5bf2334-ebb3-460f-8158-130e2e891785.jpg)
> 
> First position in the batch: ![00299-masterpiece extremely intricate fantasy an on old witch](https://user-images.githubusercontent.com/22968614/256669897-9291240a-65e1-4ae9-b3a9-9f99b38b93da.jpg)

Hello @TiagoSantos81  Do you mind sharing your workflow for this? and prompt?and modelname? This image is so much high quality I am impressed.
Do you do: text2image + hires -> img2img + ultimate sd upscale (+controlnet tiles)? What am I missing?

**Comment by vladmandic** [comment]
can you check if the issue still persists?

**Comment by TiagoSantos81** [comment]
> can you check if the issue still persists?

Unfortunately, no. Generated just now, after a `git pull -r` :
![00381-lora Tarotv0 2 0 7 masterpiece extremely intricate](https://github.com/vladmandic/automatic/assets/22968614/afd7cdbe-6724-4de3-a0b3-8023a95f0277)

The gen info is:
```
(masterpiece), (extremely intricate), fantasy, (((an on (old witch)))), (((wearing a black witch hat and black clothes))), (perfect composition:1.4), aspect ratio 1:1, beach, deviantart hd, artstation hd, concept art, detailed face and body, award-winning photography, margins, detailed face, professional oil painting by Ed Blinkey, Atey Ghailan, Jeremy Mann, Greg Manchess, Alex Gray, trending on ArtStation, trending on CGSociety, intricate, high detail, sharp focus, dramatic, award winning matte drawing cinematic lighting octane render unreal engine volumetrics dtx
Negative prompt: UnrealisticDream, (BadDream), nsfw
Steps: 20, Seed: 705512687, Sampler: DPM++ 2M SDE Karras, CFG scale: 12, Size: 384x704, Parser: A1111 parser, Model: rpg_v5, Model hash: bb7e29def5, Latent sampler: DPM++ 2M SDE Karras, Image CFG scale: 6, Denoising strength: 0.5, Refiner start: 0.5, Secondary steps: 20, Version: 8db3797, Pipeline: Original, Operations: "txt2img, hires", Dynamic thresholding enabled: True, Mimic scale: 7, Threshold percentile: 100, Hires resize: 720x1280, Hires steps: 20, Hires upscaler: Latent (nearest)
```

**Comment by vladmandic** [comment]
i just spent an hour trying to reproduce this. using different batch sizes and batch counts.
plus downloaded same model you've used and used your exact settings.
all-in-all, i cant reproduce at all.

example grid:
![image](https://github.com/vladmandic/automatic/assets/57876960/e9a5d49d-c4ee-4cf8-a220-8f55a7338d72)

**Comment by TiagoSantos81** [comment]
Mind `UnrealisticDream, (BadDream)` are embeddings, which might change the overall look, but they should not influence the duplicated head issue. 
I am also using xformers with medvram, which might not help in reproducibility. I believe I have disabled all not-preinstalled extensions on the first runs I have reported, but I will try to test that again, also without extensions.
You catch me in a busy work period, but I will try to get back to you, ASAP.

**Comment by TiagoSantos81** [comment]
I have made a clean git pull -r, and the issue seems to be solved now, although results seem to be somewhat different for other seeds. The other repo, continues to produce the same issue, despite having an effective `git pull -r`, and all extensions deactivated.
As far as I can tell, the issue is solved.
Thank you for your time looking into this and solving it.

**Comment by TiagoSantos81** [comment]
Closing this to help with maintenance. Please, reopen if it is still relevant.
