### ISSUE TITLE
[Issue]: xyz does not seem to work with ip-adapter in diffusers mode

### ISSUE THREAD

**Issue by SAC020** [vladmandic/automatic#2823]
### Issue Description

- there is no drop-down list to pick the ip adapters (adapter name), that field is now free text
- enumerating ip adapter scales has no effect on the generation, and the description of each picture generated lists ip adapter scale same as the one selected in the slider

To showcase, I have put scales 0.2 and 0.8 in xyz, and the result was two identical images with scale 0.5 (same as the interface slider)

![image](https://github.com/vladmandic/automatic/assets/50420272/aa019f91-a930-4abb-862a-94b8423caadf)

![image](https://github.com/vladmandic/automatic/assets/50420272/57ca91ca-f87f-498e-bbce-2129f18d51cd)

![image](https://github.com/vladmandic/automatic/assets/50420272/eccda209-15fd-473c-8ef2-54516bcde627)

![image](https://github.com/vladmandic/automatic/assets/50420272/3a33aa03-f50f-4aec-a445-6d071f4c9ce3)

![image](https://github.com/vladmandic/automatic/assets/50420272/5e143abc-52d0-4dc5-ac23-e346d30a65ab)

### Version Platform Description

> PS C:\ai\automatic> .\webui.bat --debug --backend diffusers --medvram
Using VENV: C:\ai\automatic\venv
16:15:26-189461 INFO     Starting SD.Next
16:15:26-192437 INFO     Logger: file="C:\ai\automatic\sdnext.log" level=DEBUG size=65 mode=create
16:15:26-193926 INFO     Python 3.10.11 on Windows
16:15:26-425394 INFO     Version: app=sd.next updated=2024-02-08 hash=376bace0
                         url=https://github.com/vladmandic/automatic/tree/master
16:15:27-000067 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11

### Relevant log output

```shell
16:20:36-107989 DEBUG    xyzgrid: x_type=52|x_values=0.2,
                         0.8|x_values_dropdown=[]|y_type=0|=|[]=[]|z_type=0|z_values=|z_values_dropdown=[]|draw_legend=T
                         rue|include_lone_images=False|include_sub_grids=False|no_grid=False|margin_size=0
16:20:36-109973 INFO     XYZ grid: images=2 grid=1 2x1 cells=1 steps=40
16:20:36-110965 DEBUG    IP adapter load: feature extractor
16:20:36-112965 DEBUG    IP adapter load: image encoder="h94/IP-Adapter/sdxl_models/image_encoder"
16:20:51-756123 INFO     IP adapter: adapter="sdxl_models/ip-adapter_sdxl.safetensors" scale=0.5 image=<PIL.Image.Image
                         image mode=RGB size=1600x1200 at 0x28438820F40> time=4.57
16:20:53-514981 DEBUG    Diffuser pipeline: StableDiffusionXLPipeline task=DiffusersTaskType.TEXT_2_IMAGE
                         set={'prompt_embeds': torch.Size([1, 77, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 77, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': device(type='cuda'), 'output_type':
                         'latent', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0.7, 'denoising_end':
                         None, 'width': 1024, 'height': 1024, 'ip_adapter_image': <class 'list'>, 'parser': 'Full
                         parser'}
16:20:53-633019 DEBUG    Sampler: sampler="DPM++ 2M" config={'num_train_timesteps': 1000, 'beta_start': 0.00085,
                         'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon',
                         'thresholding': False, 'sample_max_value': 1.0, 'algorithm_type': 'sde-dpmsolver++',
                         'solver_type': 'midpoint', 'lower_order_final': True, 'use_karras_sigmas': True,
                         'final_sigmas_type': 'zero'}
Progress  1.63s/it ███▍                                10% 2/20 00:03 00:29 Base16:20:58-252203 DEBUG    VAE load: type=taesd model=models\TAESD\taesdxl_decoder.pth
Progress  2.68it/s █████████████████████████████████ 100% 20/20 00:07 00:00 Base
16:21:10-145018 INFO     Processed: images=1 time=18.39 its=1.09 memory={'ram': {'used': 17.84, 'total': 31.92}, 'gpu':
                         {'used': 2.25, 'total': 15.99}, 'retries': 0, 'oom': 0}
16:21:14-153486 INFO     IP adapter: adapter="sdxl_models/ip-adapter_sdxl.safetensors" scale=0.5 image=<PIL.Image.Image
                         image mode=RGB size=1600x1200 at 0x28438820F40> time=3.10
16:21:14-890176 DEBUG    Diffuser pipeline: StableDiffusionXLPipeline task=DiffusersTaskType.TEXT_2_IMAGE
                         set={'prompt_embeds': torch.Size([1, 77, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 77, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': device(type='cuda'), 'output_type':
                         'latent', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0.7, 'denoising_end':
                         None, 'width': 1024, 'height': 1024, 'ip_adapter_image': <class 'list'>, 'parser': 'Full
                         parser'}
16:21:14-900924 DEBUG    Sampler: sampler="DPM++ 2M" config={'num_train_timesteps': 1000, 'beta_start': 0.00085,
                         'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon',
                         'thresholding': False, 'sample_max_value': 1.0, 'algorithm_type': 'sde-dpmsolver++',
                         'solver_type': 'midpoint', 'lower_order_final': True, 'use_karras_sigmas': True,
                         'final_sigmas_type': 'zero'}
Progress  2.92it/s █████████████████████████████████ 100% 20/20 00:06 00:00 Base
16:21:25-799786 INFO     High memory utilization: GPU=99% RAM=47% {'ram': {'used': 15.11, 'total': 31.92}, 'gpu':
                         {'used': 15.77, 'total': 15.99}, 'retries': 0, 'oom': 0}
16:21:26-131659 DEBUG    GC: collected=442 device=cuda {'ram': {'used': 15.11, 'total': 31.92}, 'gpu': {'used': 1.77,
                         'total': 15.99}, 'retries': 0, 'oom': 0} time=0.33
16:21:26-133643 INFO     Processed: images=1 time=11.98 its=1.67 memory={'ram': {'used': 15.11, 'total': 31.92}, 'gpu':
                         {'used': 1.77, 'total': 15.99}, 'retries': 0, 'oom': 0}
16:21:26-777549 DEBUG    Saving temp: image="C:\Users\sebas\AppData\Local\Temp\gradio\tmpcbvlcbf8.png"
                         resolution=2048x1184 size=1231213
```

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev branch. see screenshot below:
![image](https://github.com/vladmandic/automatic/assets/57876960/26e7ecac-1333-437e-9b0e-bac48b88db2b)

**Comment by SAC020** [comment]
Thank you. Is there a faq on how to switch to that branch? Thanks

**Comment by vladmandic** [comment]
switch to dev and update:
> git checkout dev
> git pull

and when you want to switch back to master:
> git checkout master

the sdnext launcher will autodetect which branch its working on and will autoadjust what it needs - see start of the log to verify:
> 10:18:54-657030 INFO     Version: app=sd.next updated=2024-02-09 hash=94a8f412 url=https://github.com/vladmandic/automatic/tree/dev

**Comment by SAC020** [comment]
I am sorry, but it is still not working for me


> 18:18:48-104312 INFO     Starting SD.Next
18:18:48-107288 INFO     Logger: file="C:\ai\automatic\sdnext.log" level=DEBUG size=65 mode=create
18:18:48-108776 INFO     Python 3.10.11 on Windows
**18:18:48-300828 INFO     Version: app=sd.next updated=2024-02-09 hash=12e49acb
                         url=https://github.com/vladmandic/automatic/tree/dev**
18:18:48-823944 INFO     Latest published version: 376bace04fdcc24c8a4d886f2b1b9e581cbdc754 2024-02-07T23:00:42Z
18:18:48-837503 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
18:18:48-838992 DEBUG    Setting environment tuning
18:18:48-840479 DEBUG    HF cache folder: C:\Users\sebas\.cache\huggingface\hub
18:18:48-841472 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
18:18:48-842464 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
18:18:48-844944 INFO     nVidia CUDA toolkit detected: nvidia-smi present
18:18:48-981825 DEBUG    Repository update time: Fri Feb  9 17:54:44 2024


![image](https://github.com/vladmandic/automatic/assets/50420272/bfbfbe7a-7ae8-417d-919d-f22084feaf21)

> 18:24:09-902030 DEBUG    xyzgrid: x_type=52|x_values=0.2,
                         0.8|x_values_dropdown=[]|y_type=0|dsccsdaca=dsccsdaca|[]=[]|z_type=0|z_values=|z_values_dropdow
                         n=[]|draw_legend=True|include_lone_images=True|include_sub_grids=False|no_grid=False|margin_siz
                         e=0
18:24:09-904014 INFO     XYZ grid: images=2 grid=1 2x1 cells=1 steps=40
18:24:09-905502 DEBUG    IP adapter load: feature extractor
18:24:09-906494 DEBUG    IP adapter load: image encoder="h94/IP-Adapter/sdxl_models/image_encoder"
**18:24:25-830100 INFO     IP adapter: adapter="sdxl_models/ip-adapter_sdxl.safetensors" scale=0.5 image=<PIL.Image.Image
                         image mode=RGB size=1024x1024 at 0x2C9477451E0> time=4.79**
18:24:27-730677 DEBUG    Diffuser pipeline: StableDiffusionXLPipeline task=DiffusersTaskType.TEXT_2_IMAGE
                         set={'prompt_embeds': torch.Size([1, 77, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 77, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': device(type='cuda'), 'output_type':
                         'latent', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0.7, 'denoising_end':
                         None, 'width': 1024, 'height': 1024, 'ip_adapter_image': <class 'list'>, 'parser': 'Full
                         parser'}
Progress  1.55s/it ███▍                                10% 2/20 00:03 00:27 Base18:24:32-258895 DEBUG    VAE load: type=taesd model=models\TAESD\taesdxl_decoder.pth
Progress  2.75it/s █████████████████████████████████ 100% 20/20 00:07 00:00 Base
18:24:44-279930 INFO     Processed: images=1 time=18.45 its=1.08 memory={'ram': {'used': 17.61, 'total': 31.92}, 'gpu':
                         {'used': 2.25, 'total': 15.99}, 'retries': 0, 'oom': 0}
**18:24:48-232085 INFO     IP adapter: adapter="sdxl_models/ip-adapter_sdxl.safetensors" scale=0.5 image=<PIL.Image.Image
                         image mode=RGB size=1024x1024 at 0x2C9477451E0> time=3.04**
18:24:48-992085 DEBUG    Diffuser pipeline: StableDiffusionXLPipeline task=DiffusersTaskType.TEXT_2_IMAGE
                         set={'prompt_embeds': torch.Size([1, 77, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 77, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': device(type='cuda'), 'output_type':
                         'latent', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0.7, 'denoising_end':
                         None, 'width': 1024, 'height': 1024, 'ip_adapter_image': <class 'list'>, 'parser': 'Full
                         parser'}
Progress  3.05it/s █████████████████████████████████ 100% 20/20 00:06 00:00 Base
18:24:59-475627 INFO     High memory utilization: GPU=86% RAM=45% {'ram': {'used': 14.33, 'total': 31.92}, 'gpu':
                         {'used': 13.75, 'total': 15.99}, 'retries': 0, 'oom': 0}
18:24:59-781102 DEBUG    GC: collected=521 device=cuda {'ram': {'used': 14.33, 'total': 31.92}, 'gpu': {'used': 1.72,
                         'total': 15.99}, 'retries': 0, 'oom': 0} time=0.31
18:24:59-783086 INFO     Processed: images=1 time=11.55 its=1.73 memory={'ram': {'used': 14.33, 'total': 31.92}, 'gpu':
                         {'used': 1.72, 'total': 15.99}, 'retries': 0, 'oom': 0}

![image](https://github.com/vladmandic/automatic/assets/50420272/95dfdd75-b9fe-4156-9016-c028c8de7d69)

And the [IP adapter name] is still free text

![image](https://github.com/vladmandic/automatic/assets/50420272/58c3c012-5c2a-4543-870b-5df6cc8befe7)

**Comment by SAC020** [comment]
and no, I haven't run it with a random IP adapter name, that was just to demo the issue. The scale test was done using Base SDXL ip adapter with scale 50, selected in the interface

**Comment by SAC020** [comment]
what I observe is that I have version hash=12e49acb and you have hash=94a8f412

git pull reports "up to date" and the loading log shows I am on the dev branch

**Comment by SAC020** [comment]
> yes, ip_adapter_name is free text. i don't want to lock xyz grid script to enumerate available ip adapters. and you have to enter a valid one, otherwise scale doesn't do anything. see my example.
> 
> regarding commit version, yours is one newer than mine. and there are 4 newer than that - different patches are comming in dev branch pretty much constantly.

Well, I simply disagree with that decision as it used to work just fine before, so I see this as "progress" put before user experience. 

Regardless, I am not going to argue but do my best to adapt:

- shouldn't "ip scale" xyz work on the model currently selected in the interface?
**- more (most) importantly, I have seen your example, but it is only relevant to SD1.5. What are the relevant strings for SDXL? Because I have tried their display name and they simply do not work for me, ip adapter reverts to whatever is selected in the interface** (this should be documented, btw)

Thanks

**Comment by vladmandic** [comment]
Reverting to what's selected only happens if you have it selected AND enabled - then it will take priority. If it's not enabled, it will use labels from XYZ and you should enter names as seen in the UI. 

I can add enum in the future, but let's not say "it used to work" - thats a feature request.

**Comment by SAC020** [comment]
> Reverting to what's selected only happens if you have it selected AND enabled - then it will take priority. If it's not enabled, it will use labels from XYZ and you should enter names as seen in the UI.
> 
> I can add enum in the future, but let's not say "it used to work" - thats a feature request.

Being able to drop down ("enum") xyz ip adapter models and combine with scales is a feature which worked just fine, and it was quite useful. It does not work anymore atm. So I will call it anything I need to call it as long as it works again, tyvm

- scaling: I **do** have a model selected and enabled in the interface, xyz scaling does **not** work upon it
- model names: I did my best to replicate their names, capitals included (SDXL, not SD15) in xyz, none worked; please do point me to the right naming, just in case I got it wrong, ty

If needed I will come back tomorrow morning with screenshots and logs, but I believe I've described the issues quite thoroughly and self-explanatory.

Thanks

**Comment by SAC020** [comment]
Same settings as your screenshot

> 12:34:08-162292 INFO     Version: app=sd.next updated=2024-02-10 hash=cfb059c5
                         url=https://github.com/vladmandic/automatic/tree/dev

![image](https://github.com/vladmandic/automatic/assets/50420272/5432a5a2-b6f5-4386-95ae-2190c4ab8f6d)

Log:
[ip-diffuser-log1.txt](https://github.com/vladmandic/automatic/files/14228975/ip-diffuser-log1.txt)

**Comment by vladmandic** [comment]
i've added enums to ipadapter name field.
regarding scale - it works, see screenshot below for EXACT usage.
![image](https://github.com/vladmandic/automatic/assets/57876960/c4e41017-d5fe-4387-8a86-f8ff49aace58)

**Comment by SAC020** [comment]
> i've added enums to ipadapter name field. regarding scale - it works, see screenshot below for EXACT usage. ![image](https://private-user-images.githubusercontent.com/57876960/303840296-c4e41017-d5fe-4387-8a86-f8ff49aace58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NzMwODksIm5iZiI6MTcwNzU3Mjc4OSwicGF0aCI6Ii81Nzg3Njk2MC8zMDM4NDAyOTYtYzRlNDEwMTctZDVmZS00Mzg3LThhODYtZjhmZjQ5YWFjZTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDEzNDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4N2FhN2UyOGU2ZTFmZmU0MDQ3YzQwNzNhOWM5ZWE4NDE4MzRjMjk0MDMwN2IzYTcyZGViOTU2YWJjZGQwZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4qv63BudNYYZ8YcWv93qfZUROM2_lynVZApbLX44Uto)

Thank you, I confirm it does work now. I am assuming scale only works if you call the adapter from xyz, and that didn't work for sdxl for some reason before, but now it is fixed.

Thank you for this, it is extremely helpful now that there are multiple ip adapters available for sdxl, which wasn't the case until recently.

One question please: can it possible to combine multiple ip-adapters (with multiple input images) on one run? Is this a feature that could be implemented? Thanks again

**Comment by vladmandic** [comment]
> One question please: can it possible to combine multiple ip-adapters (with multiple input images) on one run? Is this a feature that could be implemented? Thanks again

not yes, but it is on my todo list very soon.
