### ISSUE TITLE
[Issue]: vae seems to be not working

### ISSUE THREAD

**Issue by sadelcri** [vladmandic/automatic#320]
### Issue Description

basically this

![Screenshot_3](https://user-images.githubusercontent.com/120217469/233482928-9464f94d-9aad-4d50-be65-f7f5aeb99f58.png)

when I try to select vae, this error pops up and ends up crashing automatic

### Version Platform Description

windows 11, google chrome.

**Comment by vladmandic** [comment]
how are you selecting vae? in ui settings and pick from the pulldown? that should be fixed in latest update, i just tried.
if not, update here and i'll reopen.

**Comment by sadelcri** [comment]
I actually added sd_vae in the quicklist(settings, interface) so that way I can select vaes fast and so I select vaes from there, from the menu / list that is added at the top when adding sd_vae. I'm not sure but I think loras are crashing automatic too selecting them from sd_lora (the same as with sd_vae)

**Comment by sadelcri** [comment]
> how are you selecting vae? in ui settings and pick from the pulldown? that should be fixed in latest update, i just tried. if not, update here and i'll reopen.

I actually added sd_vae in the quicklist(settings, interface) so that way I can select vaes fast and so I select vaes from there, from the menu / list that is added at the top when adding sd_vae. I'm not sure but I think loras are crashing automatic too selecting them from sd_lora (the same as with sd_vae)

**Comment by vladmandic** [comment]
That's good to know. 
Is the issue still happening?
If yes, I'll reopen.

**Comment by sadelcri** [comment]
> That's good to know. Is the issue still happening? If yes, I'll reopen.


yes, still happening. I tried to delete the vae because the error was still popping but now I can't even use automatic, it pops this eror 
![Screenshot_4](https://user-images.githubusercontent.com/120217469/233569176-542e1472-fb5d-4a3b-b92a-b9b6969720c0.png)

**Comment by vladmandic** [comment]
one last question, does the issue go away if vae is removed from quicklaunch and you select it from settings instead?

**Comment by vladmandic** [comment]
@sadelcri path `your\full\path\to\vaes\vae-ft-mse-840000-ema-pruned.safetensor` does not look like a valid path, it looks like you copied that setting from some template.

otherwise, i cannot reproduce this issue. closing as resolved, if issue persists update here and i'll reopen.

**Comment by lgwjames** [comment]
> > how are you selecting vae? in ui settings and pick from the pulldown? that should be fixed in latest update, i just tried. if not, update here and i'll reopen.
> 
> I actually added sd_vae in the quicklist(settings, interface) so that way I can select vaes fast and so I select vaes from there, from the menu / list that is added at the top when adding sd_vae. I'm not sure but I think loras are crashing automatic too selecting them from sd_lora (the same as with sd_vae)

same problem here for a week, VAE drop down not showing and added to quicksettings under flux

**Comment by vladmandic** [comment]
this issue was closed 2y ago, please create a new issue.
