### ISSUE TITLE
[Issue]: Using image in FaceID via API results in error

### ISSUE THREAD

**Issue by DevilsCrypto** [vladmandic/automatic#3217]
### Issue Description

While creating the examples for the API (as pull request) i triggered a bug in FaceID.
The issue is triggered when you use FaceID for the first time after generating an image without FaceID.

So how to reproduce:
- Start SDNext
- Generate a image without the face script active, but enable **face restore**
- Now activate the face script
- Choose FaceID
- Choose FaceID Plus v2
- Upload an image to use
- Hit generate

You see an error `TypeError: sequence item 0: expected str instance, type found`. 

Now hit generate again and all works normally. But when you disable the face script and generate a normal image again with face restore, then activate face script again the first time goes wrong again.

### Version Platform Description

```
12:44:15-667281 INFO     Starting SD.Next                                                                                                                                                  
12:44:15-670119 INFO     Logger: file="/home/ubuntu/ai_api/automatic_diffusers/sdnext.log" level=INFO size=132155 mode=append                                                              
12:44:15-671090 INFO     Python 3.10.12 on Linux                                                                                                                                           
12:44:15-679414 INFO     Version: app=sd.next updated=2024-06-07 hash=84f9caaf branch=master url=https://github.com/vladmandic/automatic/tree/master                                       
12:44:15-944404 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.2.0-37-generic python=3.10.12                                                                             
12:44:15-945689 INFO     nVidia CUDA toolkit detected: nvidia-smi present                                                                                                                  
12:44:15-956628 INFO     Extensions: disabled=[]                                                                                                                                           
12:44:15-957403 INFO     Extensions: enabled=['stable-diffusion-webui-rembg', 'sd-webui-agent-scheduler', 'Lora', 'sd-extension-chainner', 'sdnext-modernui', 'sd-extension-system-info']  
                         extensions-builtin                                                                                                                                                
12:44:15-958581 INFO     Extensions: enabled=[] extensions                                                                                                                                 
12:44:15-959358 INFO     Startup: quick launch                                                                                                                                             
12:44:15-959989 INFO     Verifying requirements                                                                                                                                            
12:44:15-963771 INFO     Verifying packages                                                                                                                                                
12:44:15-964664 INFO     Extensions: disabled=[]                                                                                                                                           
12:44:15-965359 INFO     Extensions: enabled=['stable-diffusion-webui-rembg', 'sd-webui-agent-scheduler', 'Lora', 'sd-extension-chainner', 'sdnext-modernui', 'sd-extension-system-info']  
                         extensions-builtin                                                                                                                                                
12:44:15-966423 INFO     Extensions: enabled=[] extensions  
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i tried step-by-step as described above and cannot reproduce.
if you can reproduce, at least provide stacktrace of the error, not just the error title (stacktrace is printed to console)

**Comment by DevilsCrypto** [comment]
Yes i am able to reproduce it each time i do the steps:



```

13:51:41-466764 ERROR    Exception: sequence item 0: expected str instance, type found                                                                                                     
13:51:41-467757 ERROR    Arguments: args=('task(q1mlnjji7r0pwwz)', 'Masterpiece, best quality, photo of a 21 years old female, Very Short Emerald Green hair:1.2', 'nsfw, naked, easynegative, bad_prompt_version2, deepnegative, badquality, bad quality, worst  
                         quality, cropped, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation,
                         deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, malformed limbs, missing arms, missing legs, extra arms, extra  
                         legs, fused fingers, too many fingers, long neck, weird legs, malformed legs, nipple holes, inverted nipples,poorly rendered hands, black and white, grayscale,   
                         child, kid, watermark', [], 25, 10, 25, True, False, False, False, 1, 1, 6, 6, 0.7, 0, 0.5, 1, 1, -1.0, -1.0, 0, 0, 0, 768, 512, False, 0.3, 2, 'None', False, 20,
                         0, 0, 10, 0, '', '', 0, 0, 0, 0, False, 4, 0.95, False, 0.6, 1, '#000000', 0, [], 10, 1, 'None', 'None', 'None', 'None', 0.5, 0.5, 0.5, 0.5, None, None, None,    
                         None, 0, 0, 0, 0, 1, 1, 1, 1, None, None, None, None, False, '', 'None', 16, 'None', 1, True, 'None', 2, True, 1, 0, True, 'none', 3, 4, 0.25, 0.25, 'from        
                         modules.processing import process_images\n\np.width = 768\np.height = 768\np.batch_size = 2\np.steps = 10\n\nreturn process_images(p)', 2, 3, 1, 1, 0.8, 8, 64,   
                         True, 1, 1, 0.5, 0.5, False, False, 'positive', 'comma', 0, False, False, '', 'None', '', 1, '', 'None', True, 0, 'None', 2, True, 1, 0, 0, '', [], 0, '', [], 0, 
                         '', [], False, True, False, False, False, False, 0, 'FaceID', [{'name': '/tmp/gradio/tmp60q4xwaj.png', 'data':                                                    
                         'http://xxx.xxx.xxx.xxx:7800/file=/tmp/gradio/tmp60q4xwaj.png', 'is_file': True}], 'FaceID Plus v2', True, True, 1, 1, 1, 0.5, False, 'person', 1, 0.5, True)      
                         kwargs={}                                                                                                                                                         
13:51:41-472748 ERROR    gradio call: TypeError                                                                                                                                            
╭─────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────────────────────╮
│ /home/ubuntu/ai_api/automatic_diffusers/modules/call_queue.py:31 in f                                                                                                                   │
│                                                                                                                                                                                         │
│   30 │   │   │   try:                                                                                                                                                                   │
│ ❱ 31 │   │   │   │   res = func(*args, **kwargs)                                                                                                                                        │
│   32 │   │   │   │   progress.record_results(id_task, res)                                                                                                                              │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/modules/txt2img.py:90 in txt2img                                                                                                                │
│                                                                                                                                                                                         │
│    89 │   p.script_args = args                                                                                                                                                          │
│ ❱  90 │   processed = scripts.scripts_txt2img.run(p, *args)                                                                                                                             │
│    91 │   if processed is None:                                                                                                                                                         │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/modules/scripts.py:483 in run                                                                                                                   │
│                                                                                                                                                                                         │
│   482 │   │   parsed = p.per_script_args.get(script.title(), args[script.args_from:script.args_to])                                                                                     │
│ ❱ 483 │   │   processed = script.run(p, *parsed)                                                                                                                                        │
│   484 │   │   s.record(script.title())                                                                                                                                                  │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/modules/face/__init__.py:119 in run                                                                                                             │
│                                                                                                                                                                                         │
│   118 │   │   │   from modules.face.faceid import face_id                                                                                                                               │
│ ❱ 119 │   │   │   processed_images = face_id(p, app=app, source_images=input_images, model=ip_model, override=ip_override, cache=ip_cache, scale=ip_strength, structure=ip_structure) # │
│   120 │   │   │   processed = processing.Processed(p, images_list=processed_images, seed=p.seed, subseed=p.subseed, index_of_first_image=0) # manually created processed object         │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/modules/face/faceid.py:228 in face_id                                                                                                           │
│                                                                                                                                                                                         │
│   227 │   │   │   │   debug(f"FaceID: {ip_model_dict}")                                                                                                                                 │
│ ❱ 228 │   │   │   │   res = faceid_model.generate(**ip_model_dict)                                                                                                                      │
│   229 │   │   │   │   if isinstance(res, list):                                                                                                                                         │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/ip_adapter/ip_adapter_faceid.py:396 in generate                                                               │
│                                                                                                                                                                                         │
│   395 │   │                                                                                                                                                                             │
│ ❱ 396 │   │   images = self.pipe(                                                                                                                                                       │
│   397 │   │   │   prompt_embeds=prompt_embeds,                                                                                                                                          │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py:115 in decorate_context                                                            │
│                                                                                                                                                                                         │
│   114 │   │   with ctx_factory():                                                                                                                                                       │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                                                                                                          │
│   116                                                                                                                                                                                   │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py:1276 in __call__                    │
│                                                                                                                                                                                         │
│   1275 │   │   original_image = image                                                                                                                                                   │
│ ❱ 1276 │   │   init_image = self.image_processor.preprocess(                                                                                                                            │
│   1277 │   │   │   image, height=height, width=width, crops_coords=crops_coords, resize_mode=resize_mode                                                                                │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/diffusers/image_processor.py:536 in preprocess                                                                │
│                                                                                                                                                                                         │
│    535 │   │   │   raise ValueError(                                                                                                                                                    │
│ ❱  536 │   │   │   │   f"Input is in incorrect format. Currently, we only support {', '.join(supported_formats)}"                                                                       │
│    537 │   │   │   )                                                                                                                                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: sequence item 0: expected str instance, type found

```

**Comment by vladmandic** [comment]
this may already be resolved in dev if the issue is that face restore fails when there are no faces detected?
merge dev to master will happen later today, so lets revisit then - once new master is released, upgrade and try to reproduce.

**Comment by DevilsCrypto** [comment]
Unfortunately its always the first try after switching from a face_restore request. What i do now is just do a retry, and second time always succeeds with exact same data. I will switch to dev tomorrow and see if its there fixed.

**Comment by vladmandic** [comment]
dev has been merged to master, just upgrade and try.

**Comment by DevilsCrypto** [comment]
I've pulled the latest master and still have the same issue. So when i generate an image with face restore. Then switch to FaceID, the first request goes wrong. 

It complains about the input that is incorrect, but the strange thing about it is that the second request is exactly the same. So there is no difference in the contents.

```
06:34:29-322683 ERROR    API error: POST: http://155.248.196.92:8001/sdapi/v1/txt2img {'error': 'ValueError', 'code': 500, 'detail': '', 'body': '', 'errors': "Input is in incorrect      
                         format. Currently, we only support <class 'PIL.Image.Image'>, <class 'numpy.ndarray'>, <class 'torch.Tensor'>"}                                                   
06:34:29-324086 ERROR    HTTP API: ValueError                                                                                                                                              
╭─────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────────────────────╮
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/anyio/streams/memory.py:105 in receive                                                                        │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/anyio/streams/memory.py:100 in receive_nowait                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
WouldBlock

During handling of the above exception, another exception occurred:

╭─────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────────────────────╮
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/anyio/streams/memory.py:118 in receive                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

╭─────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────────────────────╮
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/starlette/middleware/base.py:159 in call_next                                                                 │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/anyio/streams/memory.py:120 in receive                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
EndOfStream

During handling of the above exception, another exception occurred:

╭─────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────────────────────╮
│ /home/ubuntu/ai_api/automatic_diffusers/modules/api/middleware.py:40 in log_and_time                                                                                                    │
│                                                                                                                                                                                         │
│   39 │   │   │   ts = time.time()                                                                                                                                                       │
│ ❱ 40 │   │   │   res: Response = await call_next(req)                                                                                                                                   │
│   41 │   │   │   duration = str(round(time.time() - ts, 4))                                                                                                                             │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/starlette/middleware/base.py:165 in call_next                                                                 │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/starlette/middleware/base.py:151 in coro                                                                      │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py:24 in __call__                                                                   │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py:44 in __call__                                                                   │
│                                                                                                                                                                                         │
│                                                                                ... 19 frames hidden ...                                                                                 │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/modules/face/faceid.py:228 in face_id                                                                                                           │
│                                                                                                                                                                                         │
│   227 │   │   │   │   debug(f"FaceID: {ip_model_dict}")                                                                                                                                 │
│ ❱ 228 │   │   │   │   res = faceid_model.generate(**ip_model_dict)                                                                                                                      │
│   229 │   │   │   │   if isinstance(res, list):                                                                                                                                         │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/ip_adapter/ip_adapter_faceid.py:396 in generate                                                               │
│                                                                                                                                                                                         │
│   395 │   │                                                                                                                                                                             │
│ ❱ 396 │   │   images = self.pipe(                                                                                                                                                       │
│   397 │   │   │   prompt_embeds=prompt_embeds,                                                                                                                                          │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py:115 in decorate_context                                                            │
│                                                                                                                                                                                         │
│   114 │   │   with ctx_factory():                                                                                                                                                       │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                                                                                                          │
│   116                                                                                                                                                                                   │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py:1277 in __call__                    │
│                                                                                                                                                                                         │
│   1276 │   │   original_image = image                                                                                                                                                   │
│ ❱ 1277 │   │   init_image = self.image_processor.preprocess(                                                                                                                            │
│   1278 │   │   │   image, height=height, width=width, crops_coords=crops_coords, resize_mode=resize_mode                                                                                │
│                                                                                                                                                                                         │
│ /home/ubuntu/ai_api/automatic_diffusers/venv/lib/python3.10/site-packages/diffusers/image_processor.py:536 in preprocess                                                                │
│                                                                                                                                                                                         │
│    535 │   │   if not is_valid_image_imagelist(image):                                                                                                                                  │
│ ❱  536 │   │   │   raise ValueError(                                                                                                                                                    │
│    537 │   │   │   │   f"Input is in incorrect format. Currently, we only support {', '.join(str(x) for x in supported_formats)}"                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Input is in incorrect format. Currently, we only support <class 'PIL.Image.Image'>, <class 'numpy.ndarray'>, <class 'torch.Tensor'>
```

**Comment by DevilsCrypto** [comment]
Okay during some debugging i found out something weird. Gonna try to explain it, forgive me if you dont understand it, but then just let me know.

So the error is triggered inside: `diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py:1277`
When i generate with face restore it goes correctly, the inpaint pipeline gets triggered because of restoring the face.

Then i switch to the FaceID first request and it gives an error in the file i mentioned above. But the strange thing is when i try to debug this and i try a second time the request never goes there. So it seems that the first time it tries to trigger the inpainting. And the second time it doesn't trigger the inpainting.

Could it be that the inpaint pipeline is loaded, and flipping to faceid triggers it the first time, and then it unloads it or something? I have tested it a lot of times, and it's always the first request that fails. The second one with same contents does the job.

**Comment by vladmandic** [comment]
you're on the right track with your analysis. but i still cannot reproduce.
can you post you actual api examples for each step?

**Comment by DevilsCrypto** [comment]
Sure, so the api calls are at follows (basically same as doing in gui):

```First api call
POST: /sdapi/v1/txt2img
{
  "prompt": "woman standing on the streets with the face towards the front",
  "negative_prompt": "uggly, bad quality",
  "steps": 25,
  "cfg_scale": 6,
  "sampler_name": "DPM++ 2M",
  "hr_sampler_name": "DPM++ 2M",
  "full_quality": True,
  "restore_faces": True,
  "denoising_strength": 0.3,
  "width": 512,
  "height": 768,
  "enable_hr": False,
  "batch_size": 1,
  "clip_skip": 1,
  "alwayson_scripts": {},
  "ip_adapter": [],
}
```
    
```Second api call
POST: /sdapi/v1/txt2img
{
  "prompt": "woman standing on the streets with the face towards the front",
  "negative_prompt": "uggly, bad quality",
  "steps": 25,
  "cfg_scale": 6,
  "sampler_name": "DPM++ 2M",
  "hr_sampler_name": "DPM++ 2M",
  "full_quality": True,
  "restore_faces": False,
  "denoising_strength": 0.3,
  "width": 512,
  "height": 768,
  "enable_hr": False,
  "batch_size": 1,
  "clip_skip": 1,
  "alwayson_scripts": {},
  "ip_adapter": [],
  "face": {'fs_cache': True,
            'id_cache': True,
            'id_conditioning': 0.5,
            'id_strength': 1,
            'ip_cache_model': True,
            'ip_model': 'FaceID Plus v2',
            'ip_override_sampler': True,
            'ip_strength': 1,
            'ip_structure': 1,
            'mode': 'FaceID',
            'pm_start': 0.5,
            'pm_strength': 1,
            'pm_trigger': 'person',
            'source_images': ['iVBORw0KGgoAAAANSUhEUgAA...']
  }
}
```

So on the second one the error occurs, and i shoot it again and goes successful. (The source images contains the base64 string, but to big to put in here.)

**Comment by vladmandic** [comment]
got it. fixed.
also note i've restuructured all api examples that ship with sdnext in `cli/api-*`, also included `api-faceid.py`
