### ISSUE TITLE
[Extension]: comfyUI full integration

### ISSUE THREAD

**Issue by angrysky56** [vladmandic/automatic#639]
### Feature description

The automatic1111 extension for comfyUI is broken badly for me but it would be ideal to be able to run comfyUI and import the modules to a more polished platform if not more stable, then people could introduce ideas that could be incorporated instantly by anyone to a linked library with all dependencies preinstalled or at least linked to good instructions for the modules and good ideas transferred into the regular ui by coders based on popularity. This was my first one- t2i2blend
![2023-04-29 (5)](https://user-images.githubusercontent.com/113643118/235333878-ad66cca4-0ad3-4647-8775-af00e1defbd1.png)

**Comment by Averytingwong** [comment]
Comfy + Vladmandic ultimate power couple imo. 😂

**Comment by vladmandic** [comment]
i never tried comfyui, but definitely why not make it compatible.
do you have a link to extension and possible contacts for intro or should i reach out?

**Comment by artafakhari** [comment]
Adding a node based flow control system like [ComfyUI](https://github.com/comfyanonymous/ComfyUI) as a part of process not the whole would be greate idea

@vladmandic I suggest you take a look at [Node-Red](https://github.com/node-red/node-red) too. You might like to implement your own `modular` ideas as a subsystem for `automatic`. ;-)

**Comment by angrysky56** [comment]
I just started trying it a couple days ago- here is some useful stuff I found.

https://app.element.io/#/room/%23comfyui_space%3Amatrix.org

https://github.com/wyrde/ComfyResources

**Comment by IkariDevGIT** [comment]
@vladmandic PLEASE add this!!!

**Comment by BinaryQuantumSoul** [comment]
> ### Feature description
> 
> The automatic1111 extension for comfyUI is broken badly for me but it would be ideal to be able to run comfyUI and import the modules to a more polished platform if not more stable, then people could introduce ideas that could be incorporated instantly by anyone to a linked library with all dependencies preinstalled or at least linked to good instructions for the modules and good ideas transferred into the regular ui by coders based on popularity. This was my first one- t2i2blend
> ![2023-04-29 (5)](https://user-images.githubusercontent.com/113643118/235333878-ad66cca4-0ad3-4647-8775-af00e1defbd1.png)
> 
> 
> ### Version Platform Description
> 
> _No response_

I'm curious about how it would be different that just having the two UIs running next to each other, what would it bring ?

**Comment by vladmandic** [comment]
> I'm curious about how it would be different that just having the two UIs running next to each other, what would it bring ?

i was wondering the same.

**Comment by ArtaFakhari** [comment]
> > ### Feature description
> > The automatic1111 extension for comfyUI is broken badly for me but it would be ideal to be able to run comfyUI and import the modules to a more polished platform if not more stable, then people could introduce ideas that could be incorporated instantly by anyone to a linked library with all dependencies preinstalled or at least linked to good instructions for the modules and good ideas transferred into the regular ui by coders based on popularity. This was my first one- t2i2blend
> > ![2023-04-29 (5)](https://user-images.githubusercontent.com/113643118/235333878-ad66cca4-0ad3-4647-8775-af00e1defbd1.png)
> > ### Version Platform Description
> > _No response_
> 
> I'm curious about how it would be different that just having the two UIs running next to each other, what would it bring ?

ComfyUI is a little bit confusing.
I think it should be amazing if we have some of its node-based features in webui.

**Comment by BinaryQuantumSoul** [comment]
> ComfyUI is a little bit confusing.
> It should be amazing if we have some of its node-based features in webui. But yes, running the whole ComfyUI inside webui is unreasonable.

So you would like to build a node-based system for WebUI that is purposely less furnished than ComfyUI? That seems like a huge effort for not so much in my opinion. I think the point of having a node-based system is to do more than what you can do with the basic WebUI so people will quickly realize limitations of the simplified WebUI node-system you're talking about and switch to ComfyUI... To be honest, ComfyUI isn't that untameable if you take the time for it. If you still want a GUI attached to it, you may take a look at projects like [this one](https://github.com/space-nuko/ComfyBox).

**Comment by ArtaFakhari** [comment]
> So you would like to build a node-based system for WebUI that is purposely less furnished than ComfyUI? That seems like a huge effort for not so much in my opinion. I think the point of having a node-based system is to do more than what you can do with the basic WebUI so people will quickly realize limitations of the simplified WebUI node-system you're talking about and switch to ComfyUI... To be honest, ComfyUI isn't that untameable if you take the time for it. If you still want a GUI attached to it, you may take a look at projects like [this one](https://github.com/space-nuko/ComfyBox).


Thank you for introducing [ComfyBox](https://github.com/space-nuko/ComfyBox). It is very close to what I had in mind, but not perfect.
I wanted to start a project that combines web UI and ComfyUI features to create something similar to [Natron](https://natrongithub.github.io/) or DaVinci Resolve. However, it would require a significant amount of time and effort.

**Comment by BinaryQuantumSoul** [comment]
> Thank you for introducing [ComfyBox](https://github.com/space-nuko/ComfyBox). It is very close to what I had in mind, but not perfect.
It's still at its first steps, so I guess you could contribute/give ideas

> I wanted to start a project that combines web UI and ComfyUI features to create something similar to [Natron](https://natrongithub.github.io/) or DaVinci Resolve. However, it would require a significant amount of time and effort.
I didn't use those so I can't say much, but yes it's a big amount of work to build a whole thing from scratch, that doesn't mean it's not a good idea, depends on how it's done and who's willing to give their time to it :)

**Comment by ArtaFakhari** [comment]
> I didn't use those so I can't say much, but yes it's a big amount of work to build a whole thing from scratch, that doesn't mean it's not a good idea, depends on how it's done and who's willing to give their time to it :)

I just installed ComfyBox
To be honest, WOW! It's really amazing
I hope @vladmandic joins the project to revolutionize it @space-nuko

**Comment by space-nuko** [comment]
Thanks for the interest, I've been working quite a lot on it. Please let me know if there's something I can improve

**Comment by ArtaFakhari** [comment]
> Thanks for the interest, I've been working quite a lot on it. Please let me know if there's something I can improve

I hope you team up with @vladmandic to make something amazing

**Comment by BinaryQuantumSoul** [comment]
I don't know if this new extension works with SD.Next https://github.com/ModelSurge/sd-webui-comfyui

**Comment by John-WL** [comment]
> I don't know if this new extension works with SD.Next https://github.com/ModelSurge/sd-webui-comfyui

This extension works with A1111 as the main supported repo, and should work in vlad. I did not try in other repos, I'm curious about if it works or not. 

We are working on adding image forwarding from txt2img/img2img output directly into ComfyUI for automated image postprocessing with nodes.

**Comment by ljleb** [comment]
> I don't know if this new extension works with SD.Next https://github.com/ModelSurge/sd-webui-comfyui

It does now https://github.com/ModelSurge/sd-webui-comfyui/pull/49

**Comment by ljleb** [comment]
PR above merged, it should work now.

**Comment by angrysky56** [comment]
Wonderful, thank you all very much. Since there are a lot of people that won't understand Comfy I suggest adding the manager or something like it with the install, clarifying where different things should be stored- ie where to put nodes, workflows, input images, etc maybe add a small tutorial to the manager, maybe make it so you can install from a node list the same way you can install from the extensions list in automatic.

https://github.com/ltdrdata/ComfyUI-Manager

The nodes are red the automatic1111 version came with.
![image](https://github.com/vladmandic/automatic/assets/113643118/e38ea62d-69d5-4623-a180-95c4d459301d)

**Comment by ljleb** [comment]
> The auto installed ComfyUI option in automatic should somehow be set to use the models, lora, TI, Controlnet already installed in automatic and the folders the user has pointed to outside automatic from the automatic settings.

This has been implemented recently, is the extension up to date?

**Comment by angrysky56** [comment]
I see it gets the models and loras etc- got the missing nodes- didn't realize it was somehow finding my old template and thought this was the default template sorry. 
Was still missing this because it isn't in the downloads in manager and got an error.
https://civitai.com/models/28238/simple-text-style-template-node-for-comfyui

Error handling request
Traceback (most recent call last):
  File "D:\automatic1111\venv\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\automatic1111\venv\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\automatic1111\venv\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\automatic1111\extensions\sd-webui-comfyui\ComfyUi\server.py", line 41, in cache_control
    response: web.Response = await handler(request)
  File "<string>", line 327, in get_object_info
  File "<string>", line 306, in node_info
  File "D:\automatic1111\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\CLIPTextFromTemplateEncode.py", line 36, in INPUT_TYPES
    cls.styles = [row for row in reader if len(row) == 3 and row[1] != "prompt" and row[0] != "None"]
  File "D:\automatic1111\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\CLIPTextFromTemplateEncode.py", line 36, in <listcomp>
    cls.styles = [row for row in reader if len(row) == 3 and row[1] != "prompt" and row[0] != "None"]
  File "C:\Users\angry\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6580: character maps to <undefined>
Error handling request
Traceback (most recent call last):
  File "D:\automatic1111\venv\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\automatic1111\venv\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\automatic1111\venv\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\automatic1111\extensions\sd-webui-comfyui\ComfyUi\server.py", line 41, in cache_control
    response: web.Response = await handler(request)
  File "<string>", line 327, in get_object_info
  File "<string>", line 306, in node_info
  File "D:\automatic1111\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\CLIPTextFromTemplateEncode.py", line 36, in INPUT_TYPES
    cls.styles = [row for row in reader if len(row) == 3 and row[1] != "prompt" and row[0] != "None"]
  File "D:\automatic1111\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\CLIPTextFromTemplateEncode.py", line 36, in <listcomp>
    cls.styles = [row for row in reader if len(row) == 3 and row[1] != "prompt" and row[0] != "None"]
  File "C:\Users\angry\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6580: character maps to <undefined>
Error handling request
Traceback (most recent call last):
  File "D:\automatic1111\venv\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\automatic1111\venv\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\automatic1111\venv\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\automatic1111\extensions\sd-webui-comfyui\ComfyUi\server.py", line 41, in cache_control
    response: web.Response = await handler(request)
  File "<string>", line 327, in get_object_info
  File "<string>", line 306, in node_info
  File "D:\automatic1111\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\CLIPTextFromTemplateEncode.py", line 36, in INPUT_TYPES
    cls.styles = [row for row in reader if len(row) == 3 and row[1] != "prompt" and row[0] != "None"]
  File "D:\automatic1111\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\CLIPTextFromTemplateEncode.py", line 36, in <listcomp>
    cls.styles = [row for row in reader if len(row) == 3 and row[1] != "prompt" and row[0] != "None"]
  File "C:\Users\angry\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6580: character maps to <undefined>

**Comment by angrysky56** [comment]
So could we get a built in node that can access the automatic styles csv- that one I shared seems to make the manager node not start. Made it so the other nodes don't load in even. I also have to refresh my browser every time I load automatic, that needs a prominent message in the UI. Thanks again.

**Comment by John-WL** [comment]
I think these issuses should be posted on ModelSurge's repo, as they aren't directly related to SD.Next.

**Comment by John-WL** [comment]
The error seems to be related to some style the extension is trying to get or parse. I don't know about the ClipTextFromTemplateEncode node, do you know where I could find it?

**Comment by angrysky56** [comment]
Having other issues with automatic now. Generates one image after using the comfy extension and won't work after that- doesn't send the one image to the automatic UI. Comfy extension is working fine lol.

[John-WL](https://github.com/John-WL) This is where I found it- 
https://civitai.com/models/28238/simple-text-style-template-node-for-comfyui

**Comment by angrysky56** [comment]
So I left comfy extension in and deleted the venv, automatic is working but the painter node is now red- so if I update comfy I think it will make automatic break until I delete the venv again. Maybe due to some conflict with that specific node?

**Comment by BinaryQuantumSoul** [comment]
Thanks @ljleb @John-WL for being quick to fix things :)
